### ISSUE TITLE
Nice work...

### ISSUE THREAD

**Issue by bioscopic** [0perationPrivacy/VoIP#10]
Tried to support by throwing a few bucks but the webpage https://dashboard.operationprivacy.com/donate didn't want to take the disposable card. Are you able to accept gift cards for a donation?

**Comment by privacyosint** [comment]
I used privacy.com cards and worked for me. Make sure you use a clean email. Might be the reason..

**Comment by privacyosint** [comment]
Try putting 5 minimum

**Comment by 0perationPrivacy** [comment]
Thanks, it's the thought that counts ;)
Pricacy.com over ProtonVPN and a simplelogin email worked for me. It's using Stripe in the backend, email is **NOT** required. You still see the receipt after a successful transaction.

**Comment by bioscopic** [comment]
$15 sent! Keep up the great work on this effort!

**Comment by privacyosint** [comment]
If everything is working, please close the post. Its makes everything netter to look for bug reports. Thank You.

**Comment by PRPSDev** [comment]
The (Optional) email field was required when I just donated. It wouldn't let me process without the email address. Either way, this is great work, and deserves contributions.

**Comment by privacyosint** [comment]
I'll let me him know, thank you

**Comment by bioscopic** [comment]
I put in a fake email and it worked for me to accept payment. i.e. thankyoufor@thisgreattool.com for example and it worked.

**Comment by privacyosint** [comment]
Will open a report

**Comment by bioscopic** [comment]
Also I was given the option to print the receipt using a fake email address.

**Comment by privacyosint** [comment]
Thank you for your help on finding this!
