### ISSUE TITLE
APPDIRECTORY config var failing

### ISSUE THREAD

**Issue by monkeysac** [0perationPrivacy/VoIP#100]
Prior to the most recent update the APPDIRECTORY config variable was working without issue. After merging the update the configured $APPDIRECTORY redirects to /404/, making the app inaccessible until the config var is removed. Further attempts to add the variable lead to same result, so the option may no longer function as expected.

**Comment by 0perationPrivacy** [comment]
let me look into it today and fix it. Thanks.
