### ISSUE TITLE
Incoming call pop-up stays open when caller hangs up

### ISSUE THREAD

**Issue by JFissionIT** [0perationPrivacy/VoIP#103]
- **Platform:** - Desktop
- **Browser:**  - Brave
- **App Version:** Latest
- **Provider:** [Telnyx, Twilio, Both] - Telnyx
- ### Describe the bug

If you do not answer, the incoming call pop-up stays open even though the caller has hung up. 

**To Reproduce**
Make an incoming call. Do not pick up. You will see the pop-up and it stays open. 

**Expected behavior**
Expect that the pop-up closes if the caller hangs up. 

**Screenshots**
See example of caller below: 

![Screenshot 22021-12-14 110354](https://user-images.githubusercontent.com/52260604/146047522-1abb6f23-4dbf-4ef5-a5de-0f9056c6ac1b.jpg)

**Comment by 0perationPrivacy** [comment]
noted, the close button comes up when the remote party hangs up, but I'll remedy it by having the app exit the screen. Thanks.

![close](https://user-images.githubusercontent.com/89225730/146041025-ed65b0dd-33b0-4b6e-949b-7eac429c4bee.png)
