### ISSUE TITLE
Cannot Save Email Settings

### ISSUE THREAD

**Issue by cheeseyfish** [0perationPrivacy/VoIP#107]
- **Platform:**  Desktop AND Mobile
- **Browser:** Firefox on Desktop, Vanadium on Mobile
- **App Version:** 0.81
- **Provider:** Twilio
- ### Describe the bug
After editing the Email Settings fields and clicking save, the previous values remain. 

**To Reproduce**
1. Have the Email Settings fields already populated. 
2. Refresh.
3. Attempt to edit the Email Settings and click "Save."
4. Observe if Email Settings were saved.

**Expected behavior**
I expect the settings to change, but it seems I cannot change them.

**Comment by cheeseyfish** [comment]
On a side note there is a typo in the Email Settings portion of the Wiki. "settings"
![image](https://user-images.githubusercontent.com/92207110/147830308-7ae058cf-2d9e-4569-ae7d-e77882474557.png)

**Comment by 0perationPrivacy** [comment]
fixed in v0.83

**Comment by 0perationPrivacy** [comment]
actually issue still remains, I have to dig deeper to find the error. Give me some more time, I'll get to it in a few days. Opening this back up.
