### ISSUE TITLE
Error message while saving settings

### ISSUE THREAD

**Issue by satirical-muzzle** [0perationPrivacy/VoIP#11]
**Platform:** [Desktop]
**Browser:** [Firefox, Brave]
**App Version:** [e.g v0.60-beta]
**Provider:** [Telnyx]
### Describe the bug
After inserting API Key from Telnyx it correctly fetches my VoIP number. I select my VoIP number from the dropdown menu. When I click "Save" an "Oops" pop-up window appears.
I close out of the settings and it appears that my profile information is saved. However, when I attempt to send a text message I get another "Oops" window stating "(Status 400) Invalid 'from' address".

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Telnyx'
3. Add API Keys
4. Click "Get number"
5. Select number from drop-down menu
6. Click "Save"
7. Error message appears

**Comment by bioscopic** [comment]
What are your logs telling you in the heroku stack? Check this area while logged into your heroku stack performing the task and see what errors it is saying.

**Comment by privacyosint** [comment]
I use telnyx, didn't have a problem. The logs show what is going on. Please share the logs. I tried 3 different numbers.

**Comment by 0perationPrivacy** [comment]
Invalid 'from' address" likely means: the from address must be digits only,....you can't have brackets or dashes.

❌(123)456-789
✅123456789
✅+1123456789
If you omit a country code, it adds "+1"

I will put in some more input validation and a regex for this field as it IS a thing I just tested it.

**Comment by privacyosint** [comment]
Did this fix your problem?

**Comment by 0perationPrivacy** [comment]
brackets and dashes ignored now in update 0.64

**Comment by satirical-muzzle** [comment]
Hi @0perationPrivacy 
I discovered the solution. My BASE_URL in my Heroku config was missing the https:// in the address.
