### ISSUE TITLE
Not receiving SMS texts from non-cellular sources

### ISSUE THREAD

**Issue by kramer9** [0perationPrivacy/VoIP#111]
Using twilio, went through the steps again on https://inteltechniques.com/voip.suite.html

Voice TwiML Bin: incoming voice
Messaging Webhook (POST): https://voip919.herokuapp.com/api/setting/receive-sms/twilio

I am receiving texts from cells and google voice, however sources like verification texts in MFA are not getting through.

I could use some help troubleshooting.  Thank you

**Comment by 0perationPrivacy** [comment]
That is a carrier issue. Most services will NOT send confirmation texts to VoIP numbers as they can identify the carriers.
