### ISSUE TITLE
Web calling on a Twillio number suddenly stopped working

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#115]
Can't place a call using a Twillio number using the web app. Call fails immediately.
Telnyx numbers work fine.

Tried hitting save under Profile Settings and clicking on override call settings but still doesn't work.

Looking into the API to see if anything changed...

**Comment by Nickfoxtel** [comment]
Hi, I'm having this same problem.  Was able to successfully sign up and register with Uptime Robot & everything, just as in the instructions.  I restarted the dynos & checked everything else that I can think of, but obviously missing something.  I enabled microphone and am attempting in Brave.  When I enter a number and try to dial out, a popup briefly flickers & a sound is made, but then it immediately disappears.  I tried allowing popups, & that did not make a difference.  

Any ideas what I might be doing wrong?
