### ISSUE TITLE
Can not send messages, but can recieve

### ISSUE THREAD

**Issue by Exhibit99** [0perationPrivacy/VoIP#116]
- **Platform:**  Desktop
- **Browser:** Firefox
- **App Version:** [e.g v0.x]
- **Provider:** Twilio

No problem receiving SMS messages, but can not send them.  The red sending line just continues.  Also noticed that my telephone number, which is the account name is red - does this indicate an issue?  Any ideas on what I ought to do to enable sending of messages?

**Comment by 0perationPrivacy** [comment]
@Exhibit99 try it now, i rebuilt the front-end, there was some glitch in the build process. It should work now. fetch the updated version 0.85.1
