### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by Exhibit99** [0perationPrivacy/VoIP#117]
- **Platform:**  Desktop
- **Browser:** Firefox and Safari
- **App Version:** Updated 12:57 GMT 15 Feb 22
- **Provider:** Telnyx

Since the update I can send messages from each of my numbers but no messages are received.

**Screenshots**

**Comment by 0perationPrivacy** [comment]
I cannot replicate the issue. I'm receiving sms's on both telnyx and twilio on the latest v0.86
And notable errors you see on the browser console that could help?
Try restarting your dyno on heroku or pressing save on your profile again to make sure the backend settings are valid.

**Comment by Exhibit99** [comment]
Thanks, I have done both things you have suggested but no impriovment. I've checked in twilio and the suite is correctly named in the web hook. I'm unusure why it would allow me to send but not recieve. There are no error codes displayed. I can send messages to each number I have, I can reply to those messages from my SIM based number/phone and it shows them as being sent, but they do not get delivered and displayed in the app. Any other ideas that I may try?

------- Original Message -------

**Comment by Exhibit99** [comment]
I have now looked in Twilio and see the errior message of:

Message Text
Show Raw

Msg	"Request to StatusCallback URL was not successful."
httpResponse	"503"
Response

------- Original Message -------

**Comment by Exhibit99** [comment]
It’s is set to global. It seems that I can send to my twilio numbers from a twilio verified number and they are received in voip suite, but if a non twilio verified number is the sender the message does not appear in the suite

**Comment by 0perationPrivacy** [comment]
Are you sure you have a paid account? Once you pay that first amount of credit, you don't need verified numbers. It seems your account is restricted.

**Comment by Exhibit99** [comment]
Yes, there is about £40 on the account and the money goes down when I make calls. I can call any number just fine

**Comment by Exhibit99** [comment]
All sorted this was an issue with Twilio
