### ISSUE TITLE
Problem Signing Up: 404 Error

### ISSUE THREAD

**Issue by Nickfoxtel-zz** [0perationPrivacy/VoIP#119]
- **Platform:**  [Desktop & Mobile]
- **Browser:** [Brave & Firefox; DDG, Mull, & Bromite]
- **App Version:** [? Recent]
- **Provider:** [Twilio]

Hi,

I'm having the same problem as some others have had with the SignUp stage.  Last year, I was able to successfully setup and SignUp for the VoIP application and had it working with a phone number. I have since released that number and decided to start the process all over again with a fresh one. The only account I kept the same was my Heroku account. And I had deleted the previous app there.

So I just started anew with the MongoDB acct. & Github creation processes, and returned to Heroku to set up a new app there. I got to the SignUp stage and attempted to create a secure username/pw, but a wiggly "404" symbol just popped up thereafter. This occurs with or without VPN enabled.
I tried adding ```SIGNUPS``` to the ```KEY``` field, and ```on``` to the ```VALUE``` field, then clicked the "Add" button. However, it didn't work, & I could only get the "404" error to pop up on screen after attempting SignUp.

Just trying to figure out what I might be missing.  I made sure to enter the password correctly (no special characters) in the db string, & yes, without the <> brackets.

**Expected behavior**
To SignUp

**Comment by 0perationPrivacy** [comment]
make sure it's not taking anything from cache and that the url bar for signups is yourusername.heroku.com/voip/signup
The the SIGNUPS variable set to on, it should work. Even if it's off, the page should still load just greyed out.

The public site page is configured the same way. Make sure you don't have the variable APPDIRECTORY configured. That can give a 404 error if the URL is not specific.
