### ISSUE TITLE
webhook return code is not a valid HTTP code when send outside sender country

### ISSUE THREAD

**Issue by PavelNL** [0perationPrivacy/VoIP#12]
[VOIP-SMS_failed_with_Telnyx_20210911_3pm.log](https://github.com/0perationPrivacy/VoIP/files/7147940/VOIP-SMS_failed_with_Telnyx_20210911_3pm.log)
[VOIP-SMS_successful_with_Telnyx_20210911_3pm.log](https://github.com/0perationPrivacy/VoIP/files/7147954/VOIP-SMS_successful_with_Telnyx_20210911_3pm.log)

**Platform:** Desktop
**Browser:** Firefox
**App Version:** Latest
**Provider:** Telnyx
### Describe the bug
Sending an SMS message from UK to NL. It is properly displayed in the WebUI. 
SMS message delivered fine and within 10s.
But in Telnyx Debug log the event is marked as failed, most likely to the code returned by OP webhook - shown in VOIP-SMS_failed_with_Telnyx_20210911_3pm.log as 0.
When the same operation is tried for sending SMS to the same number as sender, everything is fine - see VOIP-SMS_successful_with_Telnyx_20210911_3pm.log - return code is 200

**To Reproduce**
1. Send an SMS from WebUI to a number outside of sender country
2. Check Telnyx Debug log for the webhook return code (!= 200).

**Expected behavior**
Webhook should return a valid HTTP result code

**Screenshots**
see attached logs

**Comment by PavelNL** [comment]
New and more complete test case:
nbr 5 - send with curl, both initial and final logs from Telnyx are fine

[VOIP-SMS_US-UK-5_success_with_Telnyx_20210911_5pm copy.log](https://github.com/0perationPrivacy/VoIP/files/7148103/VOIP-SMS_US-UK-5_success_with_Telnyx_20210911_5pm.copy.log)

nbr 6 - send with WebUI, the initial mentioned failure, but last is fine

[VOIP-SMS_US-UK-6_and-fail_with_Telnyx_20210911_5pm.log](https://github.com/0perationPrivacy/VoIP/files/7148104/VOIP-SMS_US-UK-6_and-fail_with_Telnyx_20210911_5pm.log)

**Comment by PavelNL** [comment]
More information: behaviour (of Telnyx?), seems, is not very consistent again. While sending US->NL I'm getting both initial and delivery events failed with code=0 (instead of 200).  
I should, probably, install my own stack and provide logs from both sides.

**Comment by privacyosint** [comment]
@0perationPrivacy CC:

**Comment by privacyosint** [comment]
Look at this to see if this might fix your problem.
Issue: https://github.com/0perationPrivacy/VoIP/issues/6

**Comment by PavelNL** [comment]
Lets keep it for history. I'm not using it now, so closing. 
PS: Fix for #6 did not help.
