### ISSUE TITLE
No action upon clicking SAVE, cant add number.

### ISSUE THREAD

**Issue by Carl-VOIP** [0perationPrivacy/VoIP#120]
- **Platform:**  [Desktop]
- **Browser:** [Firefox]
- **App Version:** [e.g v0.87]
- **Provider:** [Telnyx]
- After adding Telnyx api in voip suite, selecting number from the drop down list, when we click on **SAVE**, nothing happens.
- I can confirm this is happeing with your [voip suite](https://voip.operationprivacy.com/) as well.
- NOTE : We had purchased the number, so that can not be the reason.

**To Reproduce**
1. Go to 'https://voip.operationprivacy.com/'
2. 'Create account as usual. Then Profile settings.'
3. Click on 'Telnyx and add  profile name and API.'
4. Click on 'Get Number and select the number from drop-down list.'
5. Click on SAVE.
6. See error

**Expected behavior**
Upon clicking on SAVE, there isnt any action and we cant add our number.

**Comment by 0perationPrivacy** [comment]
@Carl-VOIP are you still getting that error? Update and let me know. I did not make any changes regarding this as I could not reproduce it.

**Comment by CarlA007** [comment]
Yes it's working now after the update.
Thanks!
