### ISSUE TITLE
Similar problem to the "Web calling on a Twillio number suddenly stopped working #115" issue

### ISSUE THREAD

**Issue by Nickfoxtel** [0perationPrivacy/VoIP#122]
- **Platform:**  [Desktop]
- **Browser:** [Brave]
- **Provider:** [Twilio]
- ### Describe the bug

Hi, I'm having the same problem originally mentioned in the #115 issue. I was able to successfully sign up and register with Uptime Robot & everything, just as in the instructions. I restarted the dynos & checked everything else that I can think of, but obviously missing something. I enabled microphone and am attempting in Brave. When I enter a number and try to dial out, a popup briefly flickers & a sound is made, but then it immediately disappears. I tried allowing popups, & that did not make a difference.

Any ideas what I might be doing wrong?

**Comment by 0perationPrivacy** [comment]
Try different browsers (FF and Chrome) and see if the microphone access shows up. Update to the latest as well.
