### ISSUE TITLE
APP KILLER

### ISSUE THREAD

**Issue by jonvoip** [0perationPrivacy/VoIP#123]
- **Platform:  Desktop
- **Browser:** Firefox
- **App Version:** current as of 03/19/22
- **Provider:** Twilio
- ### Describe the bug
I had everything running great with 3 USA numbers and then I tryed to use a PR number and it caused the whole app to crash after putting the numbers  api key in the profile. I reloaded the build in heroku so I can now access my SMSWebapp account but the PR number gives me these logs and I cant make since of them. I tHing there needs to be better instuctions for how to config multiple numbers with the SMSWebapp.

**To Reproduce**
I dont know how to reproduce this outside my account

**Screenshots**
![Heroku Logs](https://user-images.githubusercontent.com/99995978/159126186-f9cee379-05c0-4bfb-8b89-dc54be4d3a42.png)

**Comment by 0perationPrivacy** [comment]
I'm looking into this but I can't see an error in your screenshot to troubleshoot.
I will try to find a way to reproduce it.
Can you define what **PR** means? I don't want to guess and look dumb 🤪.

**Comment by 0perationPrivacy** [comment]
issue #124
