### ISSUE TITLE
Heroku Security Policy Change

### ISSUE THREAD

**Issue by arctic289spice** [0perationPrivacy/VoIP#130]
- **Platform:**  Desktop
- **Browser:** Firefox
- **App Version:** v0.88
- **Provider:** Telnyx
- ### Describe the bug
Heroku has updated security policies and is no longer allowing apps to be deployed from GitHub via the Heroku Dashboard or automation.  Heroku is attempting to push users towards alternative code deployment mechanisms.  It is unclear if this is a temporary Github integration revocation or permanent.

**To Reproduce**
1. Fetch upstream on GitHub
2. Wait to see if Heroku automation takes effect.
3. Receive auto-deployment failure email from Heroku

**Expected behavior**
Heroku auto updates from GitHub.

**Screenshots**
Original email notifying of Heroku policy change
![Screenshot from 2022-04-16 14-16-12](https://user-images.githubusercontent.com/90937545/163691743-b755eee3-79bc-4c20-97df-1884aa248775.png)

Greater explanation from Heroku account
![Screenshot from 2022-04-16 14-15-08](https://user-images.githubusercontent.com/90937545/163691771-2efe0123-7010-46b7-84f0-5dba633f1454.png)

Auto deployment failure notification
![Screenshot from 2022-04-16 14-15-47](https://user-images.githubusercontent.com/90937545/163691782-841dd59b-2485-44b8-a8b9-5db68f2ea011.png)

**Comment by 0perationPrivacy** [comment]
hopefully it's temporary.
But there's an alternate way through the CLI:
https://devcenter.heroku.com/articles/heroku-cli

Once I test it, I will write it down. Or feel free to document deploying from the CLI

**Comment by satirical-muzzle** [comment]
I'm not able to access the app. Is this the same issue?
Here are the logs from Heroku (I redacted the IP and the URL):
2022-04-20T18:27:17.231989+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=[redacted].herokuapp.com request_id=df62e3d3-c611-41fa-867a-e505c0559709 fwd="194.[redacted]" dyno= connect= service= status=503 bytes= protocol=https

2022-04-20T18:27:17.986480+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=[redacted].herokuapp.com request_id=c9f7651e-a5cd-4282-b8f6-0d94ae6bea02 fwd="194.[redacted]" dyno= connect= service= status=503 bytes= protocol=https
![signal-2022-04-20-112852](https://user-images.githubusercontent.com/90492094/164298938-64c4b1e4-042f-4bc8-b8ea-fd9b168cac06.jpeg)

**Comment by 0perationPrivacy** [comment]
@satirical-muzzle Try restarting the Dyno.

**Comment by 0perationPrivacy** [comment]
try the 2 other alternatives:

https://github.com/0perationPrivacy/voip/wiki/Cloud-Hosting#e-deploy-on-render

https://github.com/0perationPrivacy/VoIP/discussions/133
