### ISSUE TITLE
Update inteltechniques.com lnk on Wiki

### ISSUE THREAD

**Issue by monkeysac** [0perationPrivacy/VoIP#134]
In "Options" section of index page, the href portion of "Follow the step-by-step guide on inteltechniques.com" links to _https://inteltechniques.com/sms.html._ This link has changed to _https://inteltechniques.com/voip.suite.html_

I'd create a pull request but I don't believe Github allows for it w/ wikis.

**Comment by 0perationPrivacy** [comment]
thanks, updated!
