### ISSUE TITLE
Setting up Telnyx profile error

### ISSUE THREAD

**Issue by zmoynihan** [0perationPrivacy/VoIP#14]
**Platform:** Desktop and Mobile
**Browser:** Firefox, and Safari
**App Version:** e.g v0.60-beta
**Provider:** Telnyx
### Describe the bug
I get an error when I enter Telnyx API when setting up the profile. In the "Add New Profile" dropdown, it only asked me to name my profile. MB's guide said there would be a choice of providers. I made up a name. Then I needed to go to settings to select Telnyx, add my API key and hit get number. When I hit save it gives me an Oops error. I then can only close the settings window with the x in the right corner. 

At this point it looks functional. My number is in the profile but every time I try to send a message, I get a status 400 error (invalid from). BTW, checking Telnyx, it shows the API key is being used.
ou expected to happen.

**Screenshots**
<img width="1095" alt="Screen Shot 2021-09-11 at 10 00 42 AM" src="https://user-images.githubusercontent.com/43887948/132955867-e1c4656e-b640-4c86-9e11-24d2045ed3bf.png">

<img width="763" alt="Screen Shot 2021-09-11 at 10 01 48 AM" src="https://user-images.githubusercontent.com/43887948/132955873-2ac78a7f-2b43-47f2-9913-a0cf43d26fc4.png">
<img width="765" alt="Screen Shot 2021-09-11 at 10 03 08 AM" src="https://user-images.githubusercontent.com/43887948/132955880-ea99915a-bafe-4be2-8206-120ed2ee6637.png">

**Comment by 0perationPrivacy** [comment]
could be an issue with the `BASE_URL` in the environment variables. check for typos and correct format there. include "https://"

**Comment by bioscopic** [comment]
> **Platform:** Desktop and Mobile
> **Browser:** Firefox, and Safari
> **App Version:** e.g v0.60-beta
> **Provider:** Telnyx
> ### Describe the bug
> 
> I get an error when I enter Telnyx API when setting up the profile. In the "Add New Profile" dropdown, it only asked me to name my profile. MB's guide said there would be a choice of providers. I made up a name. Then I needed to go to settings to select Telnyx, add my API key and hit get number. When I hit save it gives me an Oops error. I then can only close the settings window with the x in the right corner.
> 
> At this point it looks functional. My number is in the profile but every time I try to send a message, I get a status 400 error (invalid from). BTW, checking Telnyx, it shows the API key is being used.
> ou expected to happen.
> 
> **Screenshots**
> <img alt="Screen Shot 2021-09-11 at 10 00 42 AM" width="1095" src="https://user-images.githubusercontent.com/43887948/132955867-e1c4656e-b640-4c86-9e11-24d2045ed3bf.png">
> 
> <img alt="Screen Shot 2021-09-11 at 10 01 48 AM" width="763" src="https://user-images.githubusercontent.com/43887948/132955873-2ac78a7f-2b43-47f2-9913-a0cf43d26fc4.png">
> 
> <img alt="Screen Shot 2021-09-11 at 10 03 08 AM" width="765" src="https://user-images.githubusercontent.com/43887948/132955880-ea99915a-bafe-4be2-8206-120ed2ee6637.png">

Did you test with a number purchased that you "own/lease" from telnex within your telnex stack, and you're getting the error when entering your API key? Also maybe Telnex is not allowing users to use their API unless they have funded their account with more $ than just what the initial offer was if you used MBs link and got the promotional credit perhaps? Funded mine and threw Telnex some extra $ just to make sure my account didn't get flagged and to make sure everything works. I have no proof this is the issue. Just throwing it out there as a possibility. Could be the problem or just speculation. Hope you can get working!

**Comment by zmoynihan** [comment]
You all rock. It was the https:// part. 
Everything is working great. Thanks!

**Comment by 0perationPrivacy** [comment]
i need to figure out a way to put that validation in the code as it's in an env variable for ease of use. For now at least, it's in the writeup.
