### ISSUE TITLE
RIP Heroku

### ISSUE THREAD

**Issue by monkeysac** [0perationPrivacy/VoIP#150]
Taken from: https://blog.heroku.com/next-chapter

> Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users.

Are there alternatives that offer both a free tier and minimal privacy concerns? back4app.com comes up in a web search but perhaps there are others.

Hopefully this isn't EOL for the project--especially with possible development of OS-native apps...

**Comment by 0perationPrivacy** [comment]
I've been running VoIP Suite on https://render.com/ for a while now. Free, private, no issues.
in fact you can see it run on https://voip2.operationprivacy.com/
I will be migrating the primary from Heroku to Render soon.

**Comment by 0perationPrivacy** [comment]
The beauty of this app/code is that you can run it anywhere (AWS, VPS with Linux, PaaS platforms (free or paid), localhost on any machine, etc).

You can still pay for heroku $7/m, or an an AWS EC2 instance, or Render for free. You can run both db and app in a self contained Linux box on a VPS where you manage the networking, OS and application layer yourself.

Android (F-Droid) and iOS version is under development, just need time and resources to finish it. But they will still require a backend running on some cloud server. The mobile apps will be just front end apps like the web application you see now, instead running natively with notifications and updates.

**Comment by getsean** [comment]
Should current registered users use  https://voip2.operationprivacy.com/, my login worked fine..

**Comment by 0perationPrivacy** [comment]
> Should current registered users use https://voip2.operationprivacy.com/, my login worked fine..

No, stick to the main URL, i will swap the backend over to Render shortly, no one will notice a difference. I just had 2 services up for testing. Next I'll change the alternative to a few other options I'm evaluating as backups. I'll update the wiki once I've tested tertiary options.
