### ISSUE TITLE
Heroku 

### ISSUE THREAD

**Issue by bioscopic** [0perationPrivacy/VoIP#156]
- **Platform:**  [Desktop or Mobile]
- **Browser:** [Firefox, Chrome]
- **App Version:** [e.g v0.x]
- **Provider:** Heroku
- ### Describe the bug
Is anyone else not able to log into their Heroku account to delete it and update the environment to render? 

Im getting a "Problem Approving Your Request" "We can't complete your request right now. Try again later." when logging into the Heroku platform. Looks like the Heroku reverts to salesforce.com after trying to authenticate into old account.  

**To Reproduce**
1. Go to https://id.heroku.com/login
2. Click on enter username and password
3. enter your 2FA then you get "Problem Approving Your Request" "We can't complete your request right now. Try again later."

**Expected behavior**
Log into account to delete it.

**Comment by bioscopic** [comment]
Is there a way to update your environments within github to remove the Heroku and replace it with render?

**Comment by 0perationPrivacy** [comment]
> Is there a way to update your environments within github to remove the Heroku and replace it with render?

No, the whole point of an environment variable is that the value is not stored on any file, only in the memory of the environment it's running in.

**Comment by 0perationPrivacy** [comment]
My Heroku accounts work just fine with MFA.
Try different browsers, containers, etc.
Check with Heroku support.

**Comment by bioscopic** [comment]
I think Heroku has a problem with the email address used at sign up. Maybe they see it as fraud or something? If you can supply the email to support Id be grateful! I cant get into the account at all and would like to email them directly to ask what up? Worst case they will most likely kill my account once it moves to a paid only plan in November.

**Comment by 0perationPrivacy** [comment]
> I think Heroku has a problem with the email address used at sign up. Maybe they see it as fraud or something? If you can supply the email to support Id be grateful! I cant get into the account at all and would like to email them directly to ask what up? Worst case they will most likely kill my account once it moves to a paid only plan in November.

The only thing specific to you in the Heroku dyno is one env variable with the mongodb password.
**Simply go to your MongoDB account and change the password of your database.**
Besides that, the whole Heroku dyno is useless and will be deleted soon enough.

I have a simplelogin domain ending in one of my accounts, they haven't disabled that yet.
You can email them from that account or another account referencing your username.

**Comment by bioscopic** [comment]
Much appreciated! 
I wont even bother sending an email and they can kill the account.
