### ISSUE TITLE
Telnyx receive sms

### ISSUE THREAD

**Issue by 1086382** [0perationPrivacy/VoIP#158]
- **Platform:**  [Desktop]
- **Browser:** [Brave]
- **App Version:** [e.g v0.x]
- **Provider:** [Telnyx]
- ### Describe the bug
After updating, my Telnyx could send but not receive. The database can write/read correctly. The Telnyx debugger says messgae.receieved but webhook failed. Using the API v2.
Here is the webhook URL that gets populated with Telnyx https://voip-xxx.onrender.comapi/setting/receive-sms/telnyx
It looks like the forward slash between com and api was missing. Adding the slash in the fall-back webhook was the work-around.
Thanks for all your help.

**Comment by 0perationPrivacy** [comment]
you forgot to put the leading slash in the environment variable BASE_URL
Put it in there at the end, and then press save in your profile in VoIP Suite to auto update the value in the back end (Telnyx)

**Comment by 0perationPrivacy** [comment]
I'm fixing this in the next update so the app puts the slash for you if you forget.
