### ISSUE TITLE
Profile Setup

### ISSUE THREAD

**Issue by Dinosaur-Ceiling** [0perationPrivacy/VoIP#159]
- Platform: Desktop
- Browser: Firefox
- App Version: v0.89
- Provider: Twilio

Recently moved the application to Render with the recent changes with Heroku. When logging into the web app via the Render URL I am able to log in, but I am not able to setup profiles for numbers. After adding the SID and Token information the pop up asking to override the call settings appears then the following error is displaying:

SmsUrl is not valid: https://localhost/api/setting/recieve-sms/twilio

I tried manually removing the setting in the twilio dashboard as well, but it won't allow the numbers to be linked to the web app. Also tried changing the localhost part of the above URL to my Render URL, but that doesn't work either.

**Comment by 0perationPrivacy** [comment]
localhost tells me you didn't configure the BASE_URL

**Comment by Dinosaur-Ceiling** [comment]
Thank you! That was the issue. Went back into Render and added that Environment Value!

**Comment by Dinosaur-Ceiling** [comment]
There is one other issue similar to the other post ( Put leading slash #153 ). I can only send texts from the VoIP suite web app, it does not receive any. 

I went in and added the leading slash to the URL as indicated in #153 post, but this does not seem to fix the problem.
