### ISSUE TITLE
Massive Echo only coming from the speaker not the agent (VoIP)

### ISSUE THREAD

**Issue by VoiceIPRules** [0perationPrivacy/VoIP#165]
- **Platform:**  [Desktop
- **Browser:** [Chrome Brave]
- **App Version:** [e.g v0.87]
- **Provider:** [Twilio]
- ### Describe the bug
Double voice and strong Echo from the other side but not from the agent. I speak my buddy hears me normally but I hear him with a massive echo. This happened most recently on 2 calls out of 30 calls.

**To Reproduce**
1. Make a call
2. listen to your buddy
3. "enjoy" the echo
4. listen to him reporting that "everything is fine on his end"

**Expected behavior**
No echo from either side.

**Comment by 0perationPrivacy** [comment]
I don't think this can be attributed to an app issue. Unless it can be reproduced consistently. Seems like a microphone feedback problem or possibly something with the VoIP codec which the provider is responsible for.
