### ISSUE TITLE
Multiple Login not allowed!

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#17]
**Platform:** [Desktop & Mobile]
**Browser:** [any]
**App Version:** [e.g v0.62-beta]
**Provider:** [Both]
### Describe the bug
Can only log in at one place, mobile or desktop

**To Reproduce**
1. Log into mobile
2. Log into desktop
3. Receive a message
4. One of the sessions logs out, the older one.

**Expected behavior**
Should log into multiple devices

The strict cookie session implementation is doing this. Will fix is asap and push an update on 0.63

**Comment by luclefleur** [comment]
Additionally, closing the browser tab will force a new login

**Comment by 0perationPrivacy** [comment]
resolved in v0.63
