### ISSUE TITLE
PGP keys for email delivery

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#170]
Option to input the PGP public key for encrypting email that's sent using SMTP.
Email will be encrypted from the VoIP Suite server to the mailbox, using the smtp configuration as the transport. 
This way the smtp provider cannot see the emails.

**Comment by PrivacyOsint2** [comment]
We should add this in the future

**Comment by Level128** [comment]
Added in PR #198

**Comment by 0perationPrivacy** [comment]
Thank you @Level128 for your contribution and fixing some pending issues.
