### ISSUE TITLE
Can only send sms after moving to render

### ISSUE THREAD

**Issue by barrendesert** [0perationPrivacy/VoIP#172]
- **Platform:**  Desktop
- **Browser:** Firefox
- **App Version:** latest
- **Provider:** Telnyx
- ### Describe the bug
Since moving to Render from Heroku, I can no longer receive sms text messages.

I've since gone through the book and the instructions at inteltechniques to re-setup everything. 
I can make and send calls. I can send messages, but cannot receive.

**To Reproduce**
1. Everything worked in Heroku.
2. Followed voip suite instructions at [inteltechniques](https://inteltechniques.com/voip.suite.html) to setup render.
    1. Set BASE_URL env var with trailing slash as reported in other bug
3. Could send message but not receive.
4. Walked through book to setup a new Messaging Profile (but same problem)
5. New Messaging Profile setup named 'sms':
    1. Inbound Settings:
        1. Both webhook input fields set to this: https://xxxx-nnn.onrender.com/api/setting/receive-sms/telnyx (where xxxx-nnn is the name of my web service)
        2. API Version set to "Twexit API" per book instructions
    2. Number has  to 'sms' set in "Messaging Profile" dropdown

**Expected behavior**
Expect that I can receive sms text messages

**Screenshots**

**Comment by thankyoumichaelbazzell** [comment]
Having the exact same issue...did the steps twice made sure to not miss anything. Both webhook input fields are set correctly with the leading / at the end. Tried in telnyx both the v2 api which i used with heroku and the twexit api with no luck. Please help!

**Comment by thankyoumichaelbazzell** [comment]
I did notice when adding the Telnyx API key in the profile settings of the voipsuite app, if I try to override the current call settings it throws an error saying something's wrong.

**Comment by 0perationPrivacy** [comment]
That's odd, the public instance (voip.operationprivacy.com) is running on Render. I've had no issues with that so far.
Could be some manual setting in telnyx or twilio. In VoIP Suite, everytime you hit `save` on the profile settings page, it pushes those settings out to telnyx/twilio and saves it there. It overrides any other settings. So hitting `save` is usually the safest route so you don't have typos.

**Comment by satirical-muzzle** [comment]
I switched from Heroku to Render and I'm also having the same problem. I'm using Telnyx. I can send SMS fine, but not receive SMS.

**Comment by 0perationPrivacy** [comment]
> I switched from Heroku to Render and I'm also having the same problem. I'm using Telnyx. I can send SMS fine, but not receive SMS. 

So I can confirm it works on my end, using RENDER (the public instance voip.operationprivacy.com), can send and receive to/from both telnyx and twilio. Also got corresponding email notifications on message received. I used an app like TextNow to test sending the sms's.

**Comment by 0perationPrivacy** [comment]
all the settings looks right in the logs and it does say the webhook delivered.

Either refresh the app (or the whole page) and you should see it.
Or, go to `Settings > Profile > Save > No, Keep Old` That will only push the same settings back to telnyx in case you made any manual changes on your telnyx dashboard that may have messed things up.

**Comment by satirical-muzzle** [comment]
@0perationPrivacy 
I tried the three suggestions and problem persists. It is interesting the log does show the webhook delivered, but in the same Telnyx dashboard it shows the status as failed and gives a response code of 0. 
I also find it interesting that even though I am able to send SMS through the Suite the webhook logs for the sent messages as "failed" even though they successfully sent.

Through the process of switching services from Heroku to Render I did not make any changes in MongoDB or on Telnyx. 
I believe on Render I have the correct Environment Variables. BASE_URL has "https://<myinfo>.onrender.com/", COOKIE_KEY has a string of 20 randomized alpha, numeric, and special characters (not including spacebar). And I'm sure DB info is correct as I'm able to log in to VoIP Suite (I assume I wouldn't be able to log in to VoIP Suite if I didn't set this up correctly). The logs in Render also show that database connects successfully.

**Comment by satirical-muzzle** [comment]
I also noticed a mention of "high severity vulnerability" when building the web service on Render:

Nov 24 12:02:56 PM  19 packages are looking for funding
Nov 24 12:02:56 PM    run `npm fund` for details
Nov 24 12:02:56 PM  
Nov 24 12:02:56 PM  found 1 high severity vulnerability
Nov 24 12:02:56 PM    run `npm audit fix` to fix them, or `npm audit` for details
Nov 24 12:02:56 PM  ==> Generating container image from build. This may take a few minutes...
Nov 24 12:04:22 PM  ==> Uploading build...
Nov 24 12:04:52 PM  ==> Build uploaded in 24s
Nov 24 12:04:52 PM  ==> Build successful 🎉
Nov 24 12:04:52 PM  ==> Deploying...
Nov 24 12:05:12 PM  ==> Starting service with 'node app.js'

**Comment by kw1510022** [comment]
Same issue here - cant receive calls or sms

**Comment by 0perationPrivacy** [comment]
This worked for one user:

Try this in VoIP Suite:
Go to `Settings` > `Profile Settings` and hit `Save` Then click `Yes, override it`

This will override your voice settings as well. If you had configured Linphone for voice, it will replace it (not delete the Linphone settings). This action also seems to set the right webhook to receive sms's.

 I'm working on a permanent fix of this in an update once I'm confident this is what's causing the issue.
I believe I've narrowed it down to this.

**Comment by kw1510022** [comment]
When I do that I get

Error
something went wrong

I have done that a few times and I can see the changes in Telnyx but still cant receive anything

**Comment by satirical-muzzle** [comment]
I started to receive SMS today! I didn't make any changes. I took a few days off from trying after my last failed attempts. I logged in to VoIP Suite today and I see that I have messages. Telnyx also shows webhook status as "Delivered" on both send and receive whereas before it showed as "Failed" even though I was able to send.
Hopefully it stays working and is not an intermittent issue. Still have no clue why it's working now, but I'm happy that it is.

**Comment by 0perationPrivacy** [comment]
> I started to receive SMS today! I didn't make any changes. I took a few days off from trying after my last failed attempts. I logged in to VoIP Suite today and I see that I have messages. Telnyx also shows webhook status as "Delivered" on both send and receive whereas before it showed as "Failed" even though I was able to send. Hopefully it stays working and is not an intermittent issue. Still have no clue why it's working now, but I'm happy that it is.

wow, that's great! I'm still wondering what the issue was. Since the codebase never changed and it was working for most others, I'm guessing either the telecom side webhooks got confused or cached for a while or maybe Render took a while to get the webhooks. Will continue to troubleshoot passively as I further develop the code. Any and all help is appreciated! Thanks for the update 👍🏻

**Comment by 0perationPrivacy** [comment]
@satirical-muzzle I've had pretty good uptime with Render, for me I see a few minutes of downtime a month from the many free micro-services I'm running on it. What sucks is the 2-5 mins of build time. Heroku took 10-15 seconds.

Not sure why It's failing for you, check the logs section in Render to see if there's anything there.

**Comment by kw1510022** [comment]
Tonight nothing is working. I cant even get the page to come up. It's too unreliable to use.

**Comment by 0perationPrivacy** [comment]
> Tonight nothing is working. I cant even get the page to come up. It's too unreliable to use.

Options are always good in such scenarios. Heroku is still an option ($5 instead of their free services), VPS is another option some have adopted. I'm always looking for other "free" options as well that can run lightweight backend servers like this and have a relatively private signup process.

**Comment by kw1510022** [comment]
It was great for the last year but all good things come to an end. It was fantastic before the change. Thanks for all your hardwork

**Comment by 0perationPrivacy** [comment]
> It was great for the last year but all good things come to an end. It was fantastic before the change. Thanks for all your hardwork

better things to come in 2023, a native mobile app for this that actually works in GraphenOS.
More server updates to clean up the code.

**Comment by satirical-muzzle** [comment]
Logs aren't showing anything at all when the downtime occurs. It just stops logging with no errors given. The dashboard shows a green light with "Deploy succeeded" as the status.

**Comment by OfficialGitCub** [comment]
Hi - I'm having a similar issues. There does not seem to be a new messaging configuration in Twilio after setting up a Render profle. I can send texts but I do not receive them.

**Comment by OfficialGitCub** [comment]
> That's odd, the public instance (voip.operationprivacy.com) is running on Render. I've had no issues with that so far. Could be some manual setting in telnyx or twilio. In VoIP Suite, everytime you hit `save` on the profile settings page, it pushes those settings out to telnyx/twilio and saves it there. It overrides any other settings. So hitting `save` is usually the safest route so you don't have typos.

Messaging configuration is blank in Twilio after setting up profiles in Render

**Comment by ComponentClass** [comment]
Currently running this on a selfhosting configuration and I am running into the same issue. 

I have mongo set up as a docker container, and I am running the nodeJS app. 

I have configured the BASE_URL to a public domain that I own that has the 3000 port forwarded to the service (let me know if this the wrong port) 

I am currently able to send out twilio messages, but unable to receive them. 

Twilio has a webhook to the url that I am point at 3000

**Comment by huzaifa3115** [comment]
@ComponentClass although this issue is not related specifically to Voip Web, this issue must be happening from the hosting provider, can you please let me know your hosting provider?

**Comment by ComponentClass** [comment]
> i

I am currently self-hosting the services - the domain provider is under cloudflare

**Comment by huzaifa3115** [comment]
Please note if you are hosting it on any of your local systems or pc , webhook receiver will not work

**Comment by 0perationPrivacy** [comment]
> Currently running this on a selfhosting configuration and I am running into the same issue.
> 
> I have mongo set up as a docker container, and I am running the nodeJS app.
> 
> I have configured the BASE_URL to a public domain that I own that has the 3000 port forwarded to the service (let me know if this the wrong port)
> 
> I am currently able to send out twilio messages, but unable to receive them.
> 
> Twilio has a webhook to the url that I am point at 3000

Port forwarding alone will not work as the webhook in Twilio/Telnyx doesn't have a port associated with it. You will need to do static NAT for the whole domain and forward the request to the locally hosted IP address while retaining the URI.
This is the part that PaaS providers do transparently in the background.
So your NAT translated url when it hits your local server will look something like this: `https://192.168.1.10:3000/api/receive-sms....`

Also by self-hosting, some people mean hosting in the cloud like on a VPS or Azure/AWS/Rackspace, etc. Firewall rules will be different there.
If it's at home, then you must have a static IP address and your router supporting Static NAT (as opposed to Dynamic NAT or PAT) to receive webhooks consistantly. Most ISPs will provide a static IP for a few $ extra. ISPs will also block some inbound and outbound ports (namely port 25).

Since there are so many variables with self-hosting at home or on a VPS, we don't support that deployment. But it works, we use it in testing. Every environment is unique. PaaS services make the adoption so much easier. 😇

**Comment by ComponentClass** [comment]
Awesome, thank you both for the responses @huzaifa3115 @0perationPrivacy ! Appreciate it :D

**Comment by OfficialGitCub** [comment]
Just an update - still unable to receive sms. 
Peered into Twilio logs and found the error 11210 "http bad host name"

**Comment by OfficialGitCub** [comment]
sourceComponent | "14100"
httpResponse | "502"
url | REDACTED
ErrorCode | "11210"
LogLevel | "ERROR"
Msg | "HTTP bad host name"
EmailNotification | "false"

**Comment by 0perationPrivacy** [comment]
> 11210

Interesting, would love to see your URL in that particular debug output, just mask the host part to `example` or something. I'm guessing it may be a typo or a slash issue that's causing the URL to be unreachable by Twilio.
https://www.twilio.com/docs/api/errors/11200

**Comment by OfficialGitCub** [comment]
sourceComponent | "14100"
httpResponse | "502"
url | "https://0peration-privacy-example.onrender.comapi/setting/receive-sms/twilio"
ErrorCode | "11210"
LogLevel | "ERROR"
Msg | "HTTP bad host name"
EmailNotification | "false"

--
Confirming messaging webhook:

MessagingWebhook to POST: https://0peration-privacy-example.onrender.comapi/setting/receive-sms/twilio
--

**Comment by 0perationPrivacy** [comment]
@OfficialGitCub I see the mistake, your base_URL env variable should have a leading slash.
The above example should look like this:
`https://0peration-privacy-example.onrender.com/api/setting/receive-sms/twilio`
There should be a slash between `comap`

**Comment by OfficialGitCub** [comment]
@0perationPrivacy  Confirming this is fixed!! Thank you...

**Comment by 0perationPrivacy** [comment]
closing as issue seems to be fixed with the update.
