### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by sergiozygmunt** [0perationPrivacy/VoIP#183]
- **Platform:**  Desktop
- **Browser:** Chrome Version 108.0.5359.124 (Official Build) (x86_64)
- **App Version:** 0.98, commit 4bce6a6
- **Provider:** Telnyx
- ### Describe the bug
When user tries to add a Telnyx phone number to a profile, they get `Cannot read properties of undefined (reading 'id')`

**To Reproduce**
1. Create a clean environment with no users
2. Sign up and login
3. Add a profile
4. Go into "profile settings"
5. Paste the telnyx API key and pick a DID
6. Upon clicking save you will get `Cannot read properties of undefined (reading 'id')`

**Expected behavior**
Number saves correctly, as it does in the demo `[VoIP.OperationPrivacy.com](https://voip.operationprivacy.com/)`

**Screenshots**
<img width="1435" alt="Screenshot 2023-01-05 at 22 25 13" src="https://user-images.githubusercontent.com/6076316/210943582-e74929ef-7c0d-41d1-8450-f36a64d2366f.png">
<img width="607" alt="Screenshot 2023-01-05 at 22 25 23" src="https://user-images.githubusercontent.com/6076316/210943588-14139a17-aba5-43d1-8875-36bb2d262f67.png">

**Comment by sergiozygmunt** [comment]
Sorry for the bump but has anyone else run into this?

**Comment by huzaifa3115** [comment]
Yes, this is because you need to select profile from list (header->dropdown), although our team is working on error handling with proper message

**Comment by sergiozygmunt** [comment]
I have ensured that I have a profile selected, and I am still getting this error - see screenshots (API keys voided since uploading screenshots)
<img width="272" alt="Screenshot 2023-01-16 at 22 25 26" src="https://user-images.githubusercontent.com/6076316/212825067-d0105c82-e702-4202-8164-0d03e6b1d3d5.png">
<img width="271" alt="Screenshot 2023-01-16 at 22 25 22" src="https://user-images.githubusercontent.com/6076316/212825087-44d0e1b5-dcc7-4c46-896e-dd68275c0e1f.png">
<img width="790" alt="Screenshot 2023-01-16 at 22 25 01" src="https://user-images.githubusercontent.com/6076316/212825098-d2a67ea3-df51-47db-a848-c286f66f5fb3.png">
<img width="787" alt="Screenshot 2023-01-16 at 22 26 21" src="https://user-images.githubusercontent.com/6076316/212825150-e2dac84a-31ee-44f0-be36-dff195aea9e9.png">

**Comment by sergiozygmunt** [comment]
I have attached a HAR of me completing these steps:
1. Accessing the site
2. Ensuring that a profile is selected
3. Modifying the profile settings and fetching the Telnyx numbers
4. Attempting to select a number and getting the error
5. Switching profiles and repeating 2 through 4.
[voip.issue.183.har.zip](https://github.com/0perationPrivacy/VoIP/files/10431992/voip.issue.183.har.zip)

**Comment by sergiozygmunt** [comment]
I've tried deleting and re-deploying the app on both platforms with no luck - any potential other things I should check out?

**Comment by 0perationPrivacy** [comment]
when I navigate to your your domain in the logs (https://voip.safesecuretrusted.com), it prompts me for the CloudFlare Zero trust access. If that's the URL instead of (https://voip-safesecuretrusted-com.herokuapp.com), then we have an issue. Pick one, that could be blocking the api calls.

**Comment by sergiozygmunt** [comment]
I have changed the base url to voip-safesecuretrusted-com.herokuapp.com and re-deployed but still get the same error, even when accessed it via voip-safesecuretrusted-com.herokuapp.com.

**Comment by 0perationPrivacy** [comment]
if you change URLs, some references may remain in the twilio/telnyx, you will need to hit `save` on the profile window to re-write those api URLs. Make sure to do that.

**Comment by sergiozygmunt** [comment]
I have flushed cache, logged in out, created new profiles, but still get `Cannot read properties of undefined (reading 'id')`

**Comment by sergiozygmunt** [comment]
Does Operation Privacy have any commercial (paid) support options? I've tried this re-deployment like ten times and have followed all the recommended steps but aren't getting anywhere. I am still getting the same error.

**Comment by 0perationPrivacy** [comment]
> Does Operation Privacy have any commercial (paid) support options? I've tried this re-deployment like ten times and have followed all the recommended steps but aren't getting anywhere. I am still getting the same error.

No, but I'll be glad to get on a call with you to go over the setup and figure out where the issue lies. A screen share session. hit me up on the matrix chat.

**Comment by sergiozygmunt** [comment]
I fixed this by re-trying the deploy on Render (from scratch, new db everything), ensuring that I added a trailing `/` at the end of the host value - thank you to everyone for your help!

**Comment by timconsidine** [comment]
@sergiozygmunt I have run into this issue on a fresh install, using a self-hosted environment with Docker.
When you say `ensuring that I added a trailing / at the end of the host value`, are you referring to BASE_URL ?

**Comment by sergiozygmunt** [comment]
Yes, your `BASE_URL` should have a `/` at the end of it. Something like `https://voipsuite.yourdomain.com/` should work.

**Comment by timconsidine** [comment]
Thank you.
If I can get my Docker implementation working, my other recent question about TextEncoder will not be an issue.

**Comment by sergiozygmunt** [comment]
Please let me know if you do or if you have a page or something I can follow as I would also like to get it off of public cloud but was concerned with the limitations of the LSX method you previously wrote about.

**Comment by timconsidine** [comment]
Yay !
That's fixed it !
Would you be interested for me to share my Docker implementation ?
If so, how is best for you ?  Fork this repo ?  Never done that, but will stumble through.  Or a new repo ?

**Comment by sergiozygmunt** [comment]
Yeah for sure - fork is probably best, so it's easy to merge upstream changes/updates.

**Comment by 0perationPrivacy** [comment]
> Yay ! That's fixed it ! Would you be interested for me to share my Docker implementation ? If so, how is best for you ? Fork this repo ? Never done that, but will stumble through. Or a new repo ?

You can also start a `Discussion` and put in some basic procedures there for others, along with any links you like.
