### ISSUE TITLE
Beta Branch

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#19]
I would like access to the developer early releases so I can help report bugs and give solutions to problems. I would like to test the earliest builds, thanks!

**Comment by 0perationPrivacy** [comment]
Hi, really appreciate the thoughtfulness 👍🏻, right now i consider the _beta_ releases for this exact purpose, for everyone to test and let me know if there are any issue. (you're all guinea pigs lol ) I only test very quickly but not thoroughly to get it out in time. The dev repo is only for development purposes and quick testing, if I can't find anything wrong in 15 mins, i put it up for beta. **Unless you're involved in the coding process and contributing**, it wouldn't help in the flow, unless you want a 24 hour channel open with me, where I'm bugging you in the middle of the night and rushing you for answer lol. Hope you understand.

**Comment by privacyosint** [comment]
I wouldn't mind doing the 24 hour testing branch. Normally I am on the computer all week. :)

**Comment by privacyosint** [comment]
I use the 24 hour branch (Nightly) on Brave and works fine most of the time..

**Comment by privacyosint** [comment]
Email works the best. I can forward the message to my phone and computer using different email providers.

**Comment by 0perationPrivacy** [comment]
> I use the 24 hour branch (Nightly) on Brave and works fine most of the time..

I'm no `Brave` developer 🤪, I just do it as a side hobby, after hours, over the weekend! My nightly builds are disasters LOL, ask MB haha.

DM me on Element.

**Comment by privacyosint** [comment]
Could you give the link to the element website or app? Never use it. Signal or wire for me.

**Comment by 0perationPrivacy** [comment]
email me: security@operationprivacy.com

**Comment by privacyosint** [comment]
I will email you tomorrow . Going to bed, Night

**Comment by privacyosint** [comment]
Talk to you soon :)

**Comment by privacyosint** [comment]
I sent my email to you. Check your email thanks.

**Comment by privacyosint** [comment]
@0perationPrivacy
