### ISSUE TITLE
THANK YOU - email notifications?

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#2]
I got the web app working, no bugs I see yet. Will there be email notifications when a message gets in your inbox? I need this to work for a job if they need me right away by a text. (I just need to know if I got a text nothing else.) It would make me look like an idiot if I don't get there text right away.  I would forward it to tuntua email because you can get email notifications, not like proton mail. I just starting working at best buy.  
Followed the plan in the book and works great however sms notifications.

Is there any plans on email notifications?

Thank You for getting this far!!!!!!!!!

**Comment by 0perationPrivacy** [comment]
Thanks, Yes, that is in the roadmap:
https://github.com/0perationPrivacy/VoIP/projects/1#card-68323081

**Comment by privacyosint** [comment]
I did find one bug, I can't delete one of my numbers. I deleted my number out of Telnyx first. Wrong move on my part.. Then went to the web app. Says "OOPs, Number already assigned to another profile!"
It won't let me remove the old profile. The number is gone. If I try adding a new number to the profile that's in the list it gives the same error.

Thank You!

**Comment by 0perationPrivacy** [comment]
**Fetch** and update to the latest code and try again, ur 2 commits behind.
Then see if u can replicate it.

**Comment by 0perationPrivacy** [comment]
I see what you did, the logic seems to be: you deleted it from Telnyx, the app still has it connected and cant find it. It can't un-assign it either as when the API looks for that number, telnyx tells it that it doesn't exist, so it keeps it in case the API is down.
I'll put protection around this in a future bug fix.
But use only the app interface right now for that.
Thanks for pointing that out. I'll investigate.

**Comment by privacyosint** [comment]
Your Welcome, thanks for messaging me back!

**Comment by privacyosint** [comment]
Last bug I think, its small. If you refresh the page in dark mode it won't stay in dark mode. Unless you go to 'Settings' then it switches back to dark mode.

**Comment by 0perationPrivacy** [comment]
> If you refresh the page in dark mode it won't stay in dark mode. Unless you go to 'Settings' then it switches back to dark mode. Want to give this to you before the rush of people tomorrow.

Thanks, I see it. Added to my bugs fixes pipeline.
Definitely not the last bug though lol, this is just the beginning 😅

**Comment by privacyosint** [comment]
Glad I came before the podcast.

**Comment by privacyosint** [comment]
Miss clicked instead of clicking comment

**Comment by 0perationPrivacy** [comment]
> > If you refresh the page in dark mode it won't stay in dark mode. Unless you go to 'Settings' then it switches back to dark mode. Want to give this to you before the rush of people tomorrow.
> 
> Thanks, I see it. Added to my bugs fixes pipeline.
> Definitely not the last bug though lol, this is just the beginning 😅

new issue #3 opened for tracking

**Comment by privacyosint** [comment]
Thank You

**Comment by privacyosint** [comment]
Thank You, just saw both issue reports. I could have made them but I didn't know because there is no template. The templates help me. 

For example:

**Comment by privacyosint** [comment]
## Description 



## Steps to Reproduce


   1. 
   2. 
   3. 

## Actual result:



## Expected result:


## Reproduces how often: 



## Brave version (brave://version info)



## Version/Channel Information:


- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

**Comment by ironc0in** [comment]
great idea, i somehow like it concise and to the point. But that's when I understand the issue 😅, I'll take a look at integrating templates. Thanks.

**Comment by privacyosint** [comment]
Going to donate $5. Your worth it. Normally I never donate, I mean ever! Never have before. 
:)

**Comment by 0perationPrivacy** [comment]
put this under it's own issue #5

**Comment by privacyosint** [comment]
Just sent it.

**Comment by privacyosint** [comment]
@0perationPrivacy  
Last thing, I think you should put the donation link in the read.me as well because I didn't see it until later. :)


Example:
## For instructions, visit the Wiki section.

## View the Changelog

## Donation
https://dashboard.operationprivacy.com/donate

**Comment by privacyosint** [comment]
@0perationPrivacy  
I would like to use the beta of this. where is the github page? I can hopefully find bugs. :)

**Comment by 0perationPrivacy** [comment]
> @0perationPrivacy
> I would like to use the beta of this. where is the github page? I can hopefully find bugs. :)
> 
> Where should I report the beta bugs?

The alpha or DEV version is a private repo which I actively work on. It's unstable constantly up and down and focused on actively resolving a bug or a feature. When it's at a point where it's acceptable, I transfer it to the production repo (this one). Then everyone can test and report bugs I missed out on. Then rinse and repeat if it enters the cycle again. Eventually it will come out of beta once all the functions are stable enough. _(software will never be bug free)_
I can't post the dev code but I can publish the dev url I use for testing.
