### ISSUE TITLE
SMS Messages not delivered

### ISSUE THREAD

**Issue by PRPSDev** [0perationPrivacy/VoIP#20]
**Platform:** Ubuntu 21.04 
**Browser:** Chromium 93.0.4577.63
**App Version:** v. 0.64
**Provider:** Twilio
### Describe the bug
After following all detailed instructions on MB's blog, I can successfully register profiles with numbers (four in all), and apparently succeed in sending messages, but the messages are not delivered.

To be clear: I'm using the app to send messages between the four numbers, expecting that each will be able to send to one another, and receive within the app itself; however, the only thing I see in each is the outgoing message "bubble."

Twilio does not show the message in the logs, which, if I understand correctly, may be as-designed. Are there additional settings needed in Twilio to enable this app?

**To Reproduce**
1. Select a profile
2. Click Compose
3. Enter valid number (of one of the other three numbers) with + and country code as directed
4. Enter message text, and click Send Message
5. See the outgoing message bubble correctly contains the text entered in step 4.
6. Switch to destination number profile.
7. Look for messages - none are shown

**Expected behavior**
7a. Look for messages - A new message (text matching that entered in step 4) is shown from the number in the profile selected at step 1. 

**Screenshots**
N/A

**Comment by PRPSDev** [comment]
Update: Can send messages OUTBOUND to actual phones. Replies to the VoIP number do not come through  though.

**Comment by 0perationPrivacy** [comment]
Message receipt is bound to webhooks which depend on your BASE_URL being accurate. Check that in Heroku. Make sure it’s in the exact format as in the instructions

**Comment by PRPSDev** [comment]
I did double-check that... ran into an error when I had followed MB's detailed instructions first (StatusCallback URL invalid). It "works" without errors when formatted with "https://" before the subdomain. It behaves the same way with a trailing "/" as well (e.g. "https://sub.domain.com/").

Does a webhook need to be specified in Twilio's console, or does the app interact only with the API?

BTW, thanks so much for this. If you'd like more help in testing, I've been a SW quality engineer for medical devices for 20 years...

**Comment by PRPSDev** [comment]
#16 looks very similar to this issue, to me. Either we're both doing something subtly incorrect, or there's something else about the environment(s).

**Comment by 0perationPrivacy** [comment]
> I did double-check that... ran into an error when I had followed MB's detailed instructions first (StatusCallback URL invalid). It "works" without errors when formatted with "https://" before the subdomain. It behaves the same way with a trailing "/" as well (e.g. "https://sub.domain.com/").
> 
> Does a webhook need to be specified in Twilio's console, or does the app interact only with the API?
> 
> BTW, thanks so much for this. If you'd like more help in testing, I've been a SW quality engineer for medical devices for 20 years...

You do not need to change the webhooks in twilio/telnyx, the API does that. A LOT of people are not formatting the url correctly, I say just copy paste what MB wrote, it's usually the "https://" that people are leaving out. In a later update I'll make it fool proof so that even if you omit it, it will add it in. I had to do that with trailing/leading spaces.

For testing, this is the place! the Beta releases.

**Comment by privacyosint** [comment]
If this didn't solve your problem please reopen the post. Thank You

**Comment by PRPSDev** [comment]
Something else is definitely happening, but I'll be damned if I can figure it out.
If I don't give it a trailing forward-slash, then in Twilio's logs I get a "Request to StatusCallback URL was not successful" with the following URL: https://[myappsubdomain].herokuapp.comapi/setting/sms-status/twilio

Clearly, there needs to be a forward slash after .com to separate the api directory.

But once I fixed that, I still don't get any messages inbound, AND I don't see a log of it anywhere.

**Comment by privacyosint** [comment]
I had problems too but not this. Go from the top down and keep on doing that until you find what is wrong. Took me 20 times then I found it. Many hours...

**Comment by privacyosint** [comment]
Hope this helps!

**Comment by PRPSDev** [comment]
I hope so, too! So far, I'm not seeing my issue, but then, that's how these things go sometimes. Need to freshen the eyes.

**Comment by PRPSDev** [comment]
@0perationPrivacy - Problem solved - I did indeed need to kill the profiles I had created so I could reset the URL after having fixed that. Drove me quite nuts. Might want to add to Troubleshooting tips right under the URL fix note.

**Comment by 0perationPrivacy** [comment]
Thanks, I'll add it under **troubleshooting**.
This happens because a link is added in the webhook when you first add a profile. The webhook is deleted when you delete the profile. There's no way to `edit` the webhook in Twilio if you modify the env variable. This could be achieved if the URL could be edited in the GUI. I have plans to add a comprehensive settings section in the future as options grow.

**Comment by PRPSDev** [comment]
Makes sense. For a beta, this is a damned good application. Thanks for spending your time and energy on it. Amazing.
