### ISSUE TITLE
Conversation content no longer appears

### ISSUE THREAD

**Issue by github-login-1649** [0perationPrivacy/VoIP#204]
- **Platform:**  Desktop and Mobile
- **Browser:** Firefox, DDG
- **App Version:** version running on https://voip.operationprivacy.com as of July 13, 2023
- **Provider:** Telnyx
- ### Describe the bug
When I click on a conversation, the text content of the conversation does not appear.  This was not an issue as late as July 6, 2023.

**To Reproduce**
1. Go to https://voip.operationprivacy.com
2. Click on a conversation
3. See error--nothing gets loaded in the content area to the right of the list of conversations.

**Expected behavior**
When I click on a conversation, the text content should appear to the right of the conversation list.

**Comment by Level128** [comment]
@github-login-1649 let me know if v0.93 fixes this.

**Comment by github-login-1649** [comment]
Looks good now, thanks!
