### ISSUE TITLE
Changing Profile should clear or update message window

### ISSUE THREAD

**Issue by PRPSDev** [0perationPrivacy/VoIP#21]
**Platform:** Desktop (Ubuntu 21.04)
**Browser:** Chromium 93.0.4577.63
**App Version:** v0.64
**Provider:** Twilio
### Describe the bug
When switching between two profiles, the last-displayed chat is held over and continues to display after the switch. The effect is sometimes confusing, making it appear as if a message/chat was between the displayed profile and the displayed chat recipient, when it is not.

**To Reproduce**
1. Set up >1 profile.
2. Select Profile 1.
3. Send a message to a third number ("Recipient Phone Number"). The Recipient Phone Number is displayed above the chat window.
4. Switch to Profile 2.
5. Observe the chat window - it still shows the chat message sent from Profile 1 to Recipient Phone Number.

**Expected behavior**
5a. Observe the chat window - it should be blank (i.e. no chat displayed).
5b. Observe the chat window - it should display the most recent (or top) chat in the list of chats for Profile 2.

**Screenshots**
Screenshot1 = View of Profile 1 showing message sent to Recipient Phone Number.
Screenshot2 = View of Profile 2 showing message sent by Profile 1 to Recipient Phone Number.
![Screenshot1](https://user-images.githubusercontent.com/85145463/132997518-1e6845af-3e18-435d-b7d3-320e7670d194.png)
![Screenshot2](https://user-images.githubusercontent.com/85145463/132997519-e02b6bd9-3c8b-4031-8a31-4c82168b2a7f.png)

**Comment by 0perationPrivacy** [comment]
Yes. Aware of this. Will resolve this in the next update hopefully.
With multiple profiles it gets quite tricky in the backend and all the UI refreshes.

**Comment by 0perationPrivacy** [comment]
I actually checked again and I cannot reproduce it. It works fine for me. Switching profiles switches the list on the left as well. Please check again, clear cookies.

**Comment by privacyosint** [comment]
I can reproduce this problem. Mobile or desktop has it. I thought this was normal and never thought about it. It is annoying after awhile off using. Something to consider.

**Comment by 0perationPrivacy** [comment]
@PRPSDev @privacyosint 
I'm still unable to reproduce it on v0.64. I've tried linux, mac, iPhone, chrome, firefox, multiple combinations.
Try this: Sign out/sign in, clear browser cache as a new cookie feature was implemented in the last version.
Sign out and make sure ur on > 0.64 _(bottom of the login page)_

**Comment by privacyosint** [comment]
Sorry, cleared cookies. Used a new private window and still nothing.

**Comment by privacyosint** [comment]
Making everything into a nice list.

**Comment by PRPSDev** [comment]
Still does it for me, even after clearing cookies.

One other point I maybe didn't make super clear is that you need to focus/click-on a chat, then switch profiles. If you don't actually have a chat in focus then it will display the LIST of chats without issue. Only on the right-hand pane is something held over.
