### ISSUE TITLE
(Status 400) Missing whitelisted destinations

### ISSUE THREAD

**Issue by sh0ckwavevr6** [0perationPrivacy/VoIP#214]
HI, I'm not sure if this project is till maintained but I tried to setup the Voip-suite with Telnyx but I'm facing an issue when connecting with the API-Key. Telnyx return the following error **(Status 400) Missing whitelisted destinations**

Ater contacting Telnyx it they replied to me 

> In order to improve the security of Telnyx’s Messaging platform for end users, we will be implementing two changes effective March 1st, 2024:
>
>    Editing / Creating a Messaging or Verify Profile via the Portal and API will require users to configure [whitelisted destination countries](https://support.telnyx.com/en/articles/3562059-setting-up-a-messaging-profile#h_c6b0cebb82) for outbound termination.

It seems that an update is required on this project to accommodate the new requirement.

**Comment by 0perationPrivacy** [comment]
Will look into this. Seems like a setting in Telnyx to specifically allow calls to certain countries, rather than a code change. I checked my telnyx accounts and I had already put in a few countries in the allow-list. Don't remember if this was enforced when I created the profile or I just set it by myself.

**Comment by sh0ckwavevr6** [comment]
Thank you for your reply. It seems like this is something new on their end. I found a release note explaining the changes.
https://telnyx.com/release-notes/security-updates-to-messaging-api-and-portal

**Comment by sh0ckwavevr6** [comment]
Ok I play with it and now I can send SMS throug  onerender. 
But When I goes to the setting menu I got this message
The call setting is already available. Do you want to override the call setting?
![image](https://github.com/0perationPrivacy/VoIP/assets/50279424/7ae6c02b-fcc8-4fc1-b49d-9719d75dfa75)

If I click Yes I got the following error
Cannot read properties of undefined (reading 'id')
![image](https://github.com/0perationPrivacy/VoIP/assets/50279424/a07264b0-e910-4e0e-b633-0d11d48fa6c8)

Hope it's help! because on my call settings I do have country whitelisted...

**Comment by ajayyy** [comment]
Pushed a fix for this.

Without the fix, you can resolve the issue yourself by manually adding `<your-domain>/api/setting/receive-sms/telnyx` to the webhook in your messaging profile.
