### ISSUE TITLE
VoIP.MS integration

### ISSUE THREAD

**Issue by smolbytes** [0perationPrivacy/VoIP#22]
**Check the [roadmap] section first, it may already be there**
Not currently present on roadmap.

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
It would be awesome if the app also was able to utilize VoIP.MS API keys and API calls to interface with VoIP.MS numbers

**Describe alternatives you've considered**
There are paid (closed-source) mobile apps that support SIP/SIMPLE protocol for messaging, but I am trying to fully migrate to an open-source, non-Apple/Google mobile phone environment - and would like to have control over my SMS data from my voip numbers. 

**Additional context**
Thank you so much for the development work you are putting into this project, it is the answer to so many of my problems over the past few years!

**Comment by privacyosint** [comment]
Sorry to inform you, we won't be adding VOIP.ME to the road map list. There policies are not for the privacy minded, they ban accounts if not given real names.

**Comment by smolbytes** [comment]
This reply is interesting to read, given that Twilio and Telnyx also implement KYC-style validations of identity. MB even recommended the potential use of real names with VoIP services on his podcast, given the ever-growing fraud detection surrounding the phone industry. As nice as it would be to be able to acquire anonymous VoIP services directly, it is not a reality for most users, even the privacy-minded among us. 

@privacyosint @0perationPrivacy

**Comment by roundupglorify** [comment]
VoIP.MS requires an ID copy. Telnyx and Twilio do not.  My Twilio account is not in my real name. This is not possible with VoIP.MS.

**Comment by smolbytes** [comment]
@privacyosint Fair enough. Thanks for the response! I have donated to the project and will continue to because this is an awesome contribution to this community. If I can get my head wrapped around the node.js you guys used (and enough time outside of my day job) I may try to push some code your way for consideration as well. 

> 
> 
> @smolbytes
> 
> We could add this if everything is done. But there is so many things on the list.. We just don't have time or money. If I really wanted a feature so badly I would have to pay for the development to make sure it got added. If (sms to email) and (phone logs to email) don't get added, I am paying for all the develop because I need it 100% for work.. I don't care how much it costs. Yes I am broke too. However, everything takes time and money. Sadly we only have one dev here.

**Comment by 12nick12** [comment]
How much would it cost to add VoIP.ms support? All of my numbers are between VoIP.ms and Twilio.
