### ISSUE TITLE
XMR cryptocurrency wallet for donations

### ISSUE THREAD

**Issue by smolbytes** [0perationPrivacy/VoIP#24]
Please add a Monero wallet address to the donations page, in order to allow the privacy-minded among us to donate and support this great work.

**Comment by privacyosint** [comment]
We will be adding XMR and BTC as well in the future.

**Comment by privacyosint** [comment]
Put it in the wrong project. Thanks

**Comment by privacyosint** [comment]
Added go to readme.md on home page.
https://github.com/0perationPrivacy/VoIP
