### ISSUE TITLE
Null error when sending message

### ISSUE THREAD

**Issue by wbevans** [0perationPrivacy/VoIP#25]
**Platform:** Desktop
**Browser:** Firefox
**App Version:** v0.64-beta
**Provider:** Telnyx
### Describe the bug
I was able to create a profile on Telnyx. I can receive messages just fine. When I send a message, I get the following error output on the server:

```
NODE_ENV=production
database connected successfully!
/usr/src/app/app/controller/setting.controller.js:500
    message.status = status;
                   ^

TypeError: Cannot set properties of null (setting 'status')
    at exports.smsStatus (/usr/src/app/app/controller/setting.controller.js:500:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Despite the error, the message shows up in the  chat window and it gets delivered to the recipient. However, the process exits and I have to restart before doing anything else.

Note: I am hosting this in a Docker container. If I set my Docker container to always restart, this is a work-around, but the process should not be crashing every time a message is sent.

**To Reproduce**
1. Add a Telnyx profile
2. Send a message
3. Observe error output

**Expected behavior**
Server does not crash.

**Comment by privacyosint** [comment]
@0perationPrivacy CC:

**Comment by 0perationPrivacy** [comment]
although a docker environment is not supported, I will test it on the Heroku environment and check the logs. Will see if there's some error handling on that line or not and update you here.

**Comment by wbevans** [comment]
Thank you. I suspect you may be getting the error and Heroku is quickly restarting the process.

**Comment by 0perationPrivacy** [comment]
I get the error in Heroku logs as well, yet it ignores it. I'll fix it (next update), thanks for pointing it out.

**Comment by wbevans** [comment]
Thanks!

**Comment by 0perationPrivacy** [comment]
should be resolved now. Fetch the latest update

**Comment by wbevans** [comment]
Works perfectly now, thanks!
