### ISSUE TITLE
Sending Double Messages

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#26]
**Platform:** [Mobile] Haven't tried desktop
**Browser:** [Brave]
**App Version:** [Lastest]
**Provider:** [Telnyx, Twilio, Both]
### Describe the bug
Sending double Messages

**To Reproduce**
1. Type a message
2. Double click send - (Haven't tried more than 2x)
3. Sends two messages
4. There needs to be a delay or stopping function if sending the same messages within the same 3-5 secs.

Pictures:
![1](https://user-images.githubusercontent.com/90421861/133278888-76668a6e-b011-4fd2-af98-ad0bc7f43a40.png)
![2](https://user-images.githubusercontent.com/90421861/133278894-f4bafed3-6ed1-4eb9-b120-3b8aa3e6ed89.png)

**Comment by 0perationPrivacy** [comment]
interesting 🧐, will look into it and put a delay. Thanks, would have never thought of double clicking 😅
