### ISSUE TITLE
Auto scroll to latest messages (Speed Enhancement)

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#29]
**(Update)**
You fixed it, however it takes about a second to scroll down. Is there a way to scroll down while loading the page of the content then you don't have to wait anytime? I would like it to load in the background without showing it scrolling down? If this takes to much time to code and change just leave it for now and will put this in p3.

.
.
.

**Platform:** [Desktop] haven't tried mobile
**Browser:** Brave]
**App Version:** [lastest]
**Provider:** [Telnyx, Twilio, Both]

**To Reproduce**
1. Go to my message from someone. Messages much be pasted 2 pages of content.
2. click on other number messages, doesn't have to be any lengh. (For me 1 message worked)
3. Go back to original number with 1 
4. It moves the old messages in time. One page length. (Need a function to make sure it goes to the bottom of the page every time)

**Screenshots**
1 in list above. Proof. Looks normal and look at the orange bar on the left.. 
![b2](https://user-images.githubusercontent.com/90421861/133506359-ea1f240d-1c31-4a98-b8ce-02ea7c2c91c5.png)
2 Moved to new number messages
![b3](https://user-images.githubusercontent.com/90421861/133506470-9e37ceea-8c82-438b-8824-e806f88dd2c1.png)
3 This is what it looks like when refreshing the page. less than a second. Took me many tries to get this picture...
![1b](https://user-images.githubusercontent.com/90421861/133506667-aed8d833-c629-48a2-bdc9-950990125202.png)
4 After affect
![d2](https://user-images.githubusercontent.com/90421861/133507016-891fd062-60af-4a62-9f34-5f558ca9bea4.png)

Look at the time stamps of each message, these are the old messages above

**Comment by privacyosint** [comment]
@0perationPrivacy CC:

**Comment by privacyosint** [comment]
People might start having longer messages because it has been a month.

**Comment by 0perationPrivacy** [comment]
looking into it, first i thought it was just clicking, which was working fine (scrolling to the latest). But now I read it again, and it's clicking away and coming back that makes it scroll to the top. Will fix it in the next update, this weekend (bundled in with a few others).

**Comment by privacyosint** [comment]
Thank You. Much appreciated.

**Comment by privacyosint** [comment]
You fixed it, however it takes about a second to scroll down. Is there a way to scroll down while loading the page of the content then you don't have to wait anytime? I would like it to load in the background without showing me it scrolling down? If this takes to much time to code and change just leave it for now and will put this in p3. 

@0perationPrivacy

**Comment by 0perationPrivacy** [comment]
It's so fast for me i cant even notice. I can set a loading icon or something, actually there's already a loader in there. I'll see what I can do but at this point it's no longer a priority. I will likely need additional assistance from a coder to see how else the user experience can be enhanced.

**Comment by privacyosint** [comment]
ok makes sense. Remove from p3 then and put under Future Requests?
