### ISSUE TITLE
Signalwire Integration

### ISSUE THREAD

**Issue by themerchantile** [0perationPrivacy/VoIP#30]
Expand provider list to include signalwire API

**Comment by privacyosint** [comment]
Could you please explain more? Signal/Wire API

**Comment by themerchantile** [comment]
More info: https://signalwire.com/products/cloud-messaging

They are a provider similar to Telnyx and Twilio, however they offer incredible pricing ($.25/mo per # and significantly lower SMS&MMS pricing)
Connectivity to their API should be an easy integration.

**Comment by 0perationPrivacy** [comment]
I've heard about SignalWire, but can you please tell us your experience from a Privacy/Security perspective?
How easy is it to get a number? (anonymous?). Their rates are cheaper (but we're talking a few dollars here). Any other benefit vs Twilio/Telnyx (voicemail, more countries). What backend provider do they use (or they the primary VoIP provider)? Log retention, support, fraud detection, etc.

**Comment by themerchantile** [comment]
Extremely easy to sign-up, coupon codes available for large credit, noticed certain area codes/regions available that the others didn't and generally a more innovative team that is putting together webinars & easy how-to guides. For example, they just released their video api that can be used with any application (might be use case here for your project): https://developer.signalwire.com/apis/docs/making-a-zoom-clone-with-signalwire-video-apis

and more impressive is the robocall spam filter that can be spun up relatively quickly (heroku) - which should be a great addition when you decide to include inbound/outbound service to the app. https://developer.signalwire.com/apis/docs/stop-robocalls-with-signalwires-communication-api-and-nodejs

I can't comment on the privacy/security/tos/privacy policy of their service since I haven't asked, but their service/network reliability has been good. AFAIK, they use Bandwidth's infrastructure (google voice does the same).

**Comment by 0perationPrivacy** [comment]
Will definitely look into this for a list of additional providers to add. Right after all the core features are implemented and we can somewhat say that we are out of `beta`. Thanks. In the meantime, will do research on all the other other questions pertinent to this community, similar to what MB and I did for the other two.

**Comment by themerchantile** [comment]
Thank you!

**Comment by xLarco** [comment]
I went to test the onboarding process. I provided an email with a custom domain and a generic name. Got to the dashboard no problem and proceeded to test adding a sip account. Was pretty straightforward and got it connected to linphone no problem. 

However, they only offer email-based 2FA from what I can see. Second problem was when I tried to add credits to get out of trial mode. 

I added a privacy.com card to my account and it seemed they do a preauthorization charge that immediately goes away as my card icon had changed. I then go to add the credits and the card is declined. I tried a billing address closer to my VPN and was still declined. A quick google search suggested that they may block vpns from being used, so I went for public wifi and a different privacy.com card and it was still declined. I'll contact their support to see if I can resolve it but I don't have high hopes.

**Comment by privacyosint** [comment]
Thank You for testing, will be closing this post

**Comment by 0perationPrivacy** [comment]
@monkeysac it's been tagged as part of the roadmap. Will take a look at it once I re-do the settings page to accommodate for more providers. I'll test it out as well, it will go through the same scrutiny as Telnyx/Twilio went through, with policies, logs, retention, signup ease, aliases, vpn, longevity, etc.
