### ISSUE TITLE
MMS media does not send

### ISSUE THREAD

**Issue by satirical-muzzle** [0perationPrivacy/VoIP#32]
**Platform:** [Windows 10 / GrapheneOS]
**Browser:** [Firefox, Vanadium]
**Provider:** [Telnyx]
[](url)
I choose a file to send (typically jpg) and click "Open". The file does not show up in the text window / conversation. The recipient does not receive the media, but will receive the text.
Telnyx Webhook history shows that the message sent successfully, but it shows that the type of message as SMS and there is no evidence or indication of a file attached.
![MMS1](https://user-images.githubusercontent.com/90492094/134073858-daa5376c-1f3d-46b8-872f-ebdee11c23bf.jpg)

**Comment by 0perationPrivacy** [comment]
I may have addressed that or something similar in the last update v0.65.1
Update to that and let me know if that resolved it. Another update coming in a few days, I'll address it then if this didn't fix it.

**Comment by satirical-muzzle** [comment]
I updated. The image now sends on both Desktop and Phone. However, the text that sends twice when it is an MMS message. Text sends once when SMS.

**Comment by 0perationPrivacy** [comment]
> I updated. The image now sends on both Desktop and Phone. However, the text sent with the MMS message gets received twice. Text sends once when SMS.

I tried to replicate this, could not. Any other specifics? Telnyx to telnyx? telnyx to other carrier?

**Comment by satirical-muzzle** [comment]
Telnyx to Google Voice. It sends duplicate text. It receives MMS/SMS normal. I have not tested with other carriers.

**Comment by privacyosint** [comment]
Going to close this issue. If you have any other issues please let us know.
Thanks
