### ISSUE TITLE
Request: Avoid adding fonts & graphics

### ISSUE THREAD

**Issue by sesam** [0perationPrivacy/VoIP#35]
**Check the [roadmap](https://github.com/0perationPrivacy/VoIP/projects/1) section first, it may already be there**
Checked.

If there would be any tor/low bandwidth users of this app, 

**Is your feature request related to a problem? Please describe.**
A user with low bandwidth (network, processing power on their device, visual impairments) would prefer to avoid any and all not 100% necessary downloads.

**Describe the solution you'd like**
Consider not loading the custom font (Skia, seen in assets/css) and likewise for any SVG assets - if it can be done with default fonts that's better. For SVG contents, there's also svgo-action that can be used in a github pipeline to automatically optimize SVGs to make them smaller.

**Describe alternatives you've considered**
I imagine there are other options that would take more effort, i.e. using some very popular CDN source for the custom font to load it faster, but then again the browser fingerprint / IP / VoIP-site URL would be leaked to that CDN.

**Additional context**
Mayeb a strech goal, if it's quick and easy with some github action app, could be to integrate some app size tracker and decide on a budget for how slow the app is allowed to be. And maybe if most users only use one or few of the implemented providers or other features, these could be loaded on demand instead of right at the start. https://vueschool.io/articles/vuejs-tutorials/lazy-loading-and-code-splitting-in-vue-js/

**Comment by 0perationPrivacy** [comment]
- The custom font is to keep consistency, there HAS to be some element of aesthetics and branding (fonts, colors, sizes, etc). At least this one is light weight, local and not downloaded from a CDN every time.
- I decided NOT to use ANY CDNs for loading anything. No external sources to avoid load times, tracking, dependency on 3rd party services. If there are any that were missed, I'll remove them later and store a local copy (like: js, css, fonts, images, etc)
- Providers list is not loaded. Whatever API you put in, only those settings are communicated with the provider to send/receive sms's
- The App as it is, really has NO graphics (besides an ico file). I do plan to trim it down a lot more (remove unused css, js, comments, etc). But the bulk of the load doesn't exist.
- That being said, there are plans in my roadmap for stress testing, minification, faster loading etc. Right after the major functions are done and bug free to a certain level. I'll put it in the roadmap. Thanks
