### ISSUE TITLE
Lastest Update, can't login.

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#36]
After updating today's commits. I am unable to login. When you click login nothings happens.

On heroku build logs:

 Deployed 6b3fe2a7
Today at 12:54 PM · v58 · Compare diff
Build succeeded Today at 12:54 PM · View build log

I was on 4a180495 and updated to 6b3fe2a7

https://github.com/privacyosint/VoIP/compare/4a180495...6b3fe2a7

**Comment by privacyosint** [comment]
@0perationPrivacy

**Comment by 0perationPrivacy** [comment]
the public website is also running on the latest commit from today, i logged in/out, checked heroku logs, everything seems fine. Must be something else. Check in Heroku under More > View logs
https://dashboard.heroku.com/apps/[app-name]/logs

As your login fails, check the log, also in firefox/chrome, check the network tab to see what's going on and if anything fails.

**Comment by privacyosint** [comment]
2021-09-22T20:05:12.741066+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/auth/login" host=xxxx.herokuapp.com request_id=0a34e938-5fb0-4243-a4aa-422e4b14a288 fwd="MY IP" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

**Comment by privacyosint** [comment]
This is the build log:
I rebooted the build and now works. What went wrong?


-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x...
       Downloading and installing node 14.17.6...
       Using default npm version: 6.14.15
       
-----> Restoring cache
       - node_modules is checked into source control and cannot be cached
       
-----> Installing dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       Installing any new modules (package.json)
       
       > bcrypt@5.0.1 install /tmp/build_f5cc67f5/node_modules/bcrypt
       > node-pre-gyp install --fallback-to-build
       
       [bcrypt] Success: "/tmp/build_f5cc67f5/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
       added 259 packages from 347 contributors and audited 259 packages in 21.377s
       
       13 packages are looking for funding
         run `npm fund` for details
       
       found 1 critical severity vulnerability
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       audited 259 packages in 2.125s
       
       13 packages are looking for funding
         run `npm fund` for details
       
       found 1 critical severity vulnerability
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 42.2M
-----> Launching...
       Released v59
       https://voip665i5ro4cy9ktm9txr9qpkaouy.herokuapp.com/ deployed to Heroku

**Comment by 0perationPrivacy** [comment]
monogoose errors usually mean it can't reach the db. Check the string maybe? I know you probably didnt change it. Or couldn't find the username.

**Comment by privacyosint** [comment]
Should I check db?

**Comment by 0perationPrivacy** [comment]
it seems you need to give it some time, just like everything on the internet, for the caches to clear.

**Comment by 0perationPrivacy** [comment]
> Should I check db logs?

worth checking to see if it showed anything. But I doubt it. It could solve future issues with a patch somewhere if we find out why it happened (besides just doing things too quickly)

**Comment by privacyosint** [comment]
Where are the logs on db?

**Comment by privacyosint** [comment]
I give it 5 mins to update itself. It said it was finished building.

**Comment by privacyosint** [comment]
You might want to change this code a bit, https://github.com/privacyosint/VoIP/security/code-scanning/5?query=ref%3Arefs%2Fheads%2Fmain

**Comment by 0perationPrivacy** [comment]
> You might want to change this code a bit, Go to Security on my fork. Go to Code scanning. Missing rate limiting.
> https://github.com/privacyosint/VoIP/blob/6b3fe2a7f93ac92ad129c6218828b0119ea552bc/app.js#L60-L60

rate limiting was one of the first things i put on my security checklist.
It's there, I will get to it right after we finish off the contacts, email and a few other pending bugs. It may seem easy to implement, but i need to spend time testing it properly so that it doesn't break other stuff and cause more problems. I've seen a LOT of that in the past, can't afford to do that to a public repo now :P

**Comment by privacyosint** [comment]
After opening and pinning the code I think I opened a different type of request. They look all the same but are different pull requests. Wanting to pin the code for the future.
