### ISSUE TITLE
MMS not working on both platforms 

### ISSUE THREAD

**Issue by 232344235342** [0perationPrivacy/VoIP#39]
**Platform:** [Both]
**Browser:** [Chrome, Vanadium]
**App Version:** [latest]
**Provider:** [Both]

I've tried to send MMS from both Telnyx and Twilio (on web + mob), all fail. For Telnyx it appears to send, but nothing is received. Same for Twilio, however a message is actually received but it is a link to a mobile twilio URL (the link transfers to an AWS s3 link), xml code appears and states access denied. 

Receiver is a real SIM number (tried two different sim no.)

I don't really use MMS, but I thought it was worth reporting.

**Comment by privacyosint** [comment]
@0perationPrivacy CC: 

I haven't had any problems with mms. It would be beacuse you didn't follow all the steps in the guide.

**Comment by satirical-muzzle** [comment]
@232344235342 
Are you able to receive MMS? 
Have you checked the webhook logs in Telnyx and Twillio?
However, my suspicion is if it didn't work for either Telnyx of Twillio, then you might want to check heroku to ensure that your settings are correct.
Also, check to see that you fetched and merged the app code for the latest version. Refresh / log in and out of your app on all of your browsers.
Let us know if that fixed the problem.

**Comment by 232344235342** [comment]
> @232344235342
> Are you able to receive MMS?

Do you mean in general? if so, then yes. Both test phones + sims receive MMS okay. 

> Have you checked the webhook logs in Telnyx and Twillio?

I'm not really sure where to look in Twillio. The only thing I found was something called "Programmable Messaging Logs". However, I can't see any of my test messages in there.
I found the webhook logs for Telnyx however:

![1](https://user-images.githubusercontent.com/91131243/134794448-4d7c2569-b037-4434-b1c3-fbb3f2388cf5.jpg)
![2](https://user-images.githubusercontent.com/91131243/134794452-aae7c626-9d22-4247-97e9-efdd7e37a893.jpg)
![3](https://user-images.githubusercontent.com/91131243/134794454-205b1242-6548-4a00-bdb3-fe692894f1a3.jpg)

> However, my suspicion is if it didn't work for either Telnyx of Twillio, then you might want to check heroku to ensure that your settings are correct.

I re-did the installation twice, since I was originally having problems with login. Any ideas on what I should be looking for? everything else seems to work fine.

> Also, check to see that you fetched and merged the app code for the latest version. Refresh / log in and out of your app on all of your browsers.

Done, and done.

> Let us know if that fixed the problem.

Unfortunately not. Also is the app supposed to be able to receive MMS? because I've also tried sending MMS from a real sim to both Telnyx and Tw.. and both show as going through, but nothing is received on the Voip app. Kind of the exact reverse of sending from the app.

I don't know much about this kind of stuff, but could there be any issues with word wide MMS i.e. US voip to a real UK sim number?

**Comment by 0perationPrivacy** [comment]
@232344235342 Now that you mention UK number, Twilio does not support receiving messages from a UK number. It's hit or miss, their support officially pointed me to the article. Same issue discussed here:
https://github.com/0perationPrivacy/VoIP/issues/6#issuecomment-917149722

**Comment by 232344235342** [comment]
> @232344235342 Now that you mention UK number, Twilio does not support receiving messages from a UK number. It's hit or miss, their support officially pointed me to the article. Same issue discussed here:
> [#6 (comment)](https://github.com/0perationPrivacy/VoIP/issues/6#issuecomment-917149722)

Unfortunately, I don't think it's this because, it seems to fail with both Twilio and Telnyx. It also doens't work if I send from voip to sim, or to voip from sim (i.e. both ways). Perhaps, if someone else could test international MMS to real sim number, that might help test if it's only me, or a bug with the app, or the voip providers?

**Comment by privacyosint** [comment]
Going to close this issue. If you have any other issues please let us know.
Thanks
