### ISSUE TITLE
Delete number from Twilio FIRST gives error in app

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#4]
Logic error.

1. If you assign a number to one profile
2. Then delete it from Twilio or Telnyx
3. You CANNOT delete the number in the app anymore, it gives an error  ""Oops, Number already assigned to another profile!""
4. You CANNOT delete the profile, you cannot assign another number from the list in that profile either.

Solution can be to delete profile forcefully and unassign the number from the API even if it doesn't exist.

**Comment by privacyosint** [comment]
Twilio or Telynx
