### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by niconfus** [0perationPrivacy/VoIP#41]
Please consider adding an [open source license](https://choosealicense.com) to the project to give the legal right to use, modify, and self-host this project. Otherwise, the code is considered all rights reserved and using it could be a copyright violation.

**Comment by privacyosint** [comment]
@0perationPrivacy CC:

**Comment by privacyosint** [comment]
@0perationPrivacy What do you think about this?

**Comment by 0perationPrivacy** [comment]
I've considered this before the project release as well. Still considering how to do it right. It will happen eventually. Right now in **Beta** I'm getting pounded with criticism, un-called for "pentests", people copying code/idea without any attribution or mention of inspiration,......Let the dust settle, I'm not about to sue anyone for using my code 😅, don't worry, it's not worth my time. This is a LONG term hobby project for me.

**Comment by bioscopic** [comment]
You're doing great work @0perationPrivacy, we all know who to attribute this great work to. Going to give a little more $ soon to show ongoing support!

**Comment by 0perationPrivacy** [comment]
open source license officially added.
