### ISSUE TITLE
Unable to sign up - getting "unhandled promise rejection" error in Heroku App

### ISSUE THREAD

**Issue by JFissionIT** [0perationPrivacy/VoIP#42]
**Platform:** [Desktop or Mobile]
Desktop - Windows10
**Browser:** [e.g. Firefox, Chrome, Safari, Brave]
Edge (chromium)
**App Version:** [e.g v0.60-beta]
latest on github
**Provider:** [Telnyx, Twilio, Both]
Not there yet. 
### Describe the bug
_A clear and concise description of what the bug is_

Followed the steps to setup this app using cloud method (Heroku/MongoDB). Application starts up fine. However, I'm unable to sign-up. No error on browser. However, when checking the Heroku app logs, I see this error: 

`(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-09-26T19:11:15.245822+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Checking the Edge browser F12 developer network log, I found this: 

Cannot POST /api/api/auth/get-signup
HTTP 404 Not Found response

**To Reproduce**
1. Go to:  https://jvoip.herokuapp.com
2. Click on: Try to sign-up
4. See error: Nothing happens - No error code. 

**Expected behavior**
Expect to sign up. It appears it's not connecting to mongodb. On the mongodb side, there are no logs that I can see but I'm new to heroku/mongo. Thank you - excited about this app and want to check it out and provide feedback. 

**Screenshots**

**Comment by JFissionIT** [comment]
Update: I realized I had the connection string wrong. I updated it by grabbing the string from MongoDB Connect Your Application pop-up, and this time I'm no longer seeing the unhandled promise rejection errors.  I restarted the Dynos and connection to Database was successful. Finally was able to create a new login. All set!

**Comment by privacyosint** [comment]
That's good news.
