### ISSUE TITLE
New update seems to have broken heroku automatic deployment then fixed its self

### ISSUE THREAD

**Issue by 232344235342** [0perationPrivacy/VoIP#43]
I'm unsure what happened, but after updating to the latest commit 027e497. I received an email from heroku stating automatic deployment failed. I tried reconnecting to Github as they recommended as well as few other things such as restarting dynos. Nothing seemed to work.
From my best guess waiting about an hour, then hitting 'deploy branch', got it to work. 
I figured, I would let the devs/community know incase it happens to anyone else.

![2](https://user-images.githubusercontent.com/91131243/134887936-1746fada-517d-45bf-80a5-27b3d114db8c.jpg)
![1](https://user-images.githubusercontent.com/91131243/134887948-f1989e69-9ff9-41a7-ae53-322ae8ee8fbe.jpg)
![3](https://user-images.githubusercontent.com/91131243/134887954-ef4cbacb-15fa-4dd0-bd41-af1fc2af6955.jpg)

**Comment by bioscopic** [comment]
I just updated to the latest commit 027e497 saw my environment change from pending for a few minutes then back to active. Looks like everything is running smooth. Maybe it takes longer to fix if you have a lot of message traffic, MMS, etc that needs to be updated. This update I was looking at the change log fixes/updates the following: "Memory issues/buffer crashes fixed for heroku" Probably OK to close this unless others have issues that don't resolve the problem in their heroku stack...
