### ISSUE TITLE
Additional profile pulls assigned DID

### ISSUE THREAD

**Issue by JFissionIT** [0perationPrivacy/VoIP#45]
**Platform:** [Desktop or Mobile]
Win10
**Browser:** [e.g. Firefox, Chrome, Safari, Brave]
Edge
**App Version:** [e.g v0.60-beta]
v0.65.2-beta
**Provider:** [Telnyx, Twilio, Both]
Telnyx
### Describe the bug
_When adding a 2nd profile, I see an already assigned DID in the drop-down menu without even adding an API key_

**To Reproduce**
1. Go to 'Add New Profile'
2. Click on 'Save.'
3. Scroll down to 'Settings.'
4. You will see previously assigned DID in drop down. You can even select it and Save successfully. 

However, it will not work and do not expect it to work because it's already assigned to another profile. 

**Expected behavior**
I do not expect anything in the dropdown until a new API key is added. App also allows you to save it but I don't think that should be allowed. 

**Screenshots**
![profile2](https://user-images.githubusercontent.com/52260604/135014977-7510eae3-f543-4236-ac27-c69d1ca6d1ca.png)

**Comment by privacyosint** [comment]
We want to make it easier to add other numbers with the same API Key, that's why we have that how it is. It would make things more complicated. If you auto fill the api key, people will be upset with that. I use two different accounts for myself.  This is the best way. Any other options I am not looking at?

**Comment by JFissionIT** [comment]
Well, my observation was not that we're missing an API key as much as it's listing a DID that's already assigned to another profile. I think there's going to me confusing here because an API key can have multiple DIDs, but it doesn't seem like a DID can be assigned to multiple accounts (at least I don't think that's a good idea). 

Problem I see the carrier support thus far is that each user of this app would need a Telnyx account. Since I manage many DIDs with SMS feature, I would prefer creating dedicated API keys which lists the DIDs they own. Not sure if Telnyx supports this but I can find out.

**Comment by 0perationPrivacy** [comment]
> Well, my observation was not that we're missing an API key as much as it's listing a DID that's already assigned to another profile. I think there's going to me confusing here because an API key can have multiple DIDs, but it doesn't seem like a DID can be assigned to multiple accounts (at least I don't think that's a good idea).
> 
> Problem I see the carrier support thus far is that each user of this app would need a Telnyx account. Since I manage many DIDs with SMS feature, I would prefer creating dedicated API keys which lists the DIDs they own. Not sure if Telnyx supports this but I can find out.

I understand this, I will address this in a fix. It's taking the list from a cache. But once you put in a new API key and press the button, it will refresh with an updated list of DIDs for that API. Right now it's just defaulting the dropdown to the last updated list. Will get it fixed soon. Until then, I'll keep this open.
Thanks.

**Comment by 0perationPrivacy** [comment]
fixed this, will push it out in an update with some other fixes tomorrow sometime. Then I'll close this.
