### ISSUE TITLE
I followed the steps from the inteltechniques.com and got everything set up, but now I have a problem with sign up. The button simply doesn't react.

### ISSUE THREAD

**Issue by avesatan666** [0perationPrivacy/VoIP#48]
I followed the steps from the inteltechniques.com and got everything set up, but now I have a problem with sign up. The button simply doesn't react. 
Any advice on what I might have done wrong and how to fix it?

_Originally posted by @avesatan666 in https://github.com/0perationPrivacy/VoIP/discussions/47_

**Comment by bioscopic** [comment]
The guide is solid. You will have to be more specific. What button are you referring to in order to get more help from the community?

**Comment by 0perationPrivacy** [comment]
most problems arise with the **db** link not correct. Make sure the password in the mongodb link has no special characters and no brackets around it < >

**Comment by avesatan666** [comment]
I followed the instructions and indeed I made an error with password in mongodb database and the link was therefore incorrect. It is now fixed and working. Thank you!
