### ISSUE TITLE
Can receive messages

### ISSUE THREAD

**Issue by avesatan666** [0perationPrivacy/VoIP#50]
**Platform:** [Ubuntu]
**Browser:** [Firefox]
**Provider:** Twilio, Both

After adding my twilio number I can send messages just fine to my mobile carrier, but I can receive messages back from the same number (it is a British number). Any ideas of might have gone wrong?
![desktop](https://user-images.githubusercontent.com/91639629/135759480-79dc163d-e325-419c-8443-7542d1ead256.png)

![phone](https://user-images.githubusercontent.com/91639629/135759484-dd2b2757-bb8e-4df4-8df8-63208e6fb003.png)

**Comment by ZGoldman8** [comment]
I believe you meant you _can't_ receive messages back from your phone. I am having the same issue where the app can send messages but can't receive them. Interestingly it only affects 1 of the 3 phone Twilio numbers I've imported. The other 2 work fine, and I can't figure out why.

**Comment by 0perationPrivacy** [comment]
Check out issue #6 
Twilio / Telnyx have issues with UK and most international numbers.

**Comment by avesatan666** [comment]
Yes that's what I meant, I can't receive messages back from my phone.

**Comment by avesatan666** [comment]
I don't think its an issue with international numbers, both twilio and mobile number are UK numbers.

**Comment by 0perationPrivacy** [comment]
> I don't think its an issue with international numbers, both twilio and mobile number are UK numbers.

A non-US number is an international number (=UK). 
read my 2 correspondences with Telnyx and Twilio, they both said they don’t support inbound messages from UK numbers specifically. It’s an issue between providers of these countries.

**Comment by ZGoldman8** [comment]
The issue on my end was resolved by deleting the profile and re-adding it. It works now. Mine is a US number.

**Comment by privacyosint** [comment]
Going to close this issue. If you have any other issues please let us know. 
Thanks
