### ISSUE TITLE
Can't Login Once I Fork This GitHub?

### ISSUE THREAD

**Issue by GitHubQueenn** [0perationPrivacy/VoIP#51]
Hi. I followed all of Mike's instruction on his blog post (set up MongoDB, Heroku, and GitHub) and when I go to my own Heroku site address to login, I enter my username/password but when I click "Login," nothing happens. At the bottom of the login area, it also says, "New registrations are disabled," but I never made that an option (yet). I am using the login user/pass that was in the MongoDB string that I entered into Heroku's "DB" config var.

Help? To add: I do not see any "Sign Up" button on my login page.

**Comment by GitHubQueenn** [comment]
@0perationPrivacy ?

**Comment by 0perationPrivacy** [comment]
Hi, sorry, the signup variables was `off` by default in my last commit. I set it back to `on`.
You can change it in Heroku to `on` (SIGNUPS = on).
Signup, and use those credentials to log in, not the mongodb ones, those are only for your backend connection to your own db.

**Comment by GitHubQueenn** [comment]
> Hi, sorry, the signup variables was `off` by default in my last commit. I set it back to `on`.
> You can change it in Heroku to `on` (SIGNUPS = on).
> Signup, and use those credentials to log in, not the mongodb ones, those are only for your backend connection to your own db.

Ok, I enabled the sign up page but when I fill in a username and password and click on “Sign Up,” nothing happens. The page doesn’t do anything.

**Comment by 0perationPrivacy** [comment]
then ur mongodb string may not be correct.
Make sure the password you set up in mongodb doesnt have any special characters and you removed the two brackets `<` `>`

**Comment by privacyosint** [comment]
If you have any other issues please let us know.
Thanks

**Comment by GitHubQueenn** [comment]
It must’ve been using a special character in the password. Works now, thanks.

**Comment by cheeseyfish** [comment]
> > Hi, sorry, the signup variables was `off` by default in my last commit. I set it back to `on`.
> > You can change it in Heroku to `on` (SIGNUPS = on).
> > Signup, and use those credentials to log in, not the mongodb ones, those are only for your backend connection to your own db.
> 
> Ok, I enabled the sign up page but when I fill in a username and password and click on “Sign Up,” nothing happens. The page doesn’t do anything.

How exactly did you enable the signup page? Same issue here.
