### ISSUE TITLE
Will There Be An App For This? 

### ISSUE THREAD

**Issue by GitHubQueenn** [0perationPrivacy/VoIP#53]
Hi. Will there be an app for this project or some sort of way to have it on my mobile phone and get push notifications?

**Comment by bioscopic** [comment]
Check the project roadmap.

**Comment by 0perationPrivacy** [comment]
Yes, apk and iOS app will be there once all the main features are implemented and bugs ironed out.
Right now you can set this app as a PWA (Progressive Web App), open it in a mobile browser and save it as a shortcut on your home screen. It will look just like a regular app, with the exception of push notifications.
