### ISSUE TITLE
Create a dockerized, self hostable version

### ISSUE THREAD

**Issue by fightforprivacy** [0perationPrivacy/VoIP#56]
**Is your feature request related to a problem? Please describe.**
Currently, this is only hostable via online databases that control your data. 
Since we are a privacy community, we should place an emphasis on controlling EVERY aspect of our data

**Describe the solution you'd like**
I should be able to deploy this on my own server, whether local or not. This package should also be made available to Yunohost, cloudron, and other related services.

**Describe alternatives you've considered**
A cloudron user has created this repository, https://github.com/timconsidine/LXC-OperationPrivacy-VOIP, as a temporary workaround, but it is not beginner user friendly

**Comment by privacyosint** [comment]
Please check out the discussion for docker. We got it working ish.. https://github.com/0perationPrivacy/VoIP/discussions/49

If you need anything docker please go to the discussion, thanks.
