### ISSUE TITLE
Project Wiki - Web Application Firewall

### ISSUE THREAD

**Issue by monkeysac** [0perationPrivacy/VoIP#57]
Apologies for opening an Issue here for something not directly related to code / functionality.  

The Wiki currently suggests using Cloudflare WAF as a frontend for the VoIP web app hosted on Heroku.  While its an excellent (and desired) end state I feel there should be more transparency about the means to achieve it.

The CF services suggested **will essentially act to MITM** any traffic you have flowing through the web app, therefore making interception & storage feasible for them and/or anyone with access to their servers.  While this may come down to assessing what's worse between CF visibility (privacy anyone?) and access restrictions for certain countries (also ideal) I'd rather not have someone  looking up the skirt of my VoIP solution of choice.

I'm not familiar enough with Heroku to suggest an alternative and all of their "firewall" options appear to be 3rd party add-ons.  Heck, you can't even mandate HTTPS which is unfortunate.   For starters, is it even possible to bundle with Nginx (to proxy for webapp) and Certbot (for SSL)?

**Comment by 0perationPrivacy** [comment]
While this is a VoIP SMS app, I'm trying to keep it modular so you are not tied down to one technology, that includes WAF.
I've implemented many WAFs in my career, honestly speaking, CloudFlare has been the easiest AND EXTREMELY effective.

For a cloud based app, this is the most feasible solution (free and quick with pretty decent privacy).
For hosting on a VPS, it depends, if it's on NGINX, you can use ModSecurity (now maintained by F5), there's IPTables, full on appliances like F5 BIG-IP, etc.

On my task list I've put in a few native firewall features in Node.js like bruteforce protection (coming soon in a future update) and whole bunch of other easy ones.

Hosting on Heroku gives you their domain which already has the certificate on it, so you don't need to worry about letsencrypt. In self hosting, that's your headache.

I'll keep the app independent of the WAF but the above are my suggestions. Feel free to suggest better options for this use case (also looking at other apps on how they do it would help - hint, all enterprise apps use enterprise grade dedicated WAF appliances $$$)

**Comment by monkeysac** [comment]
> Remember this is still considered beta and insecure. Not as private as we all want, but better than the telco providing us the service. We now have some control over the infrastructure. It will mature with time, I guarantee you that.

Agreed on all points.  I'm very excited to see where this project goes!

**Comment by 0perationPrivacy** [comment]
> > Remember this is still considered beta and insecure. Not as private as we all want, but better than the telco providing us the service. We now have some control over the infrastructure. It will mature with time, I guarantee you that.
> 
> Agreed on all points. I'm very excited to see where this project goes!
> 
> Edit: Also if you end up charging for an app or turnkey access to the services please dont restrict payment to the dang play/app stores (looking at you, mysudo)! :)

I will never charge for this app. It will eventually be on iOS and Android, always **free**. The donation option will always be open. If I wanted to make money from this, I would have had 10 other ideas. (You just have to bare with me juggling between 10 projects right now 😅)
Enjoy 😇!
