### ISSUE TITLE
Can't edit contact number information (3 Small Issues inside of 1)

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#58]
**Platform:** [Desktop or Mobile]
**Browser:** [Brave]
**App Version:** [v0.66-beta]
**Provider:** [NA]
### Describe the bug
Can't edit a contact number with adding a plus (+).

Issue 1
**To Reproduce**
1. Make a contact
2. Don't put a + Example: 12223334444 (1 is always needed such as +1)
3. Forgot to put +
4. Edit the number try to put +12223334444
5. Doesn't work when clicking save.
6. Update:
You can't change anything inside of the number after creating the contact.

Issue 2
1. Delete Contact
2. Add a new Contact
3. That number you added and everything you had on the new contact is still there even after deleting it the contact. 
4. Should be blank when creating a new contact from scratch.
5. If you reload the page-refresh. 
6. Add a new Contact - There is no content.

Issue 3 - Never Mind. Have to do more testing, give me a few days. THANKS
1. Try to send a message when you don't have +
2. Won't let you send the message
3. If you don't have a +1 could put a what if statement to auto add +1 everytime before you add contact.
4. Give a number like this: 2223334444
5. But it gives me a number on the contacts as +12223334444
6. Makes it easier for people to add contacts.

**Comment by 0perationPrivacy** [comment]
i fixed this, will push out a new update tomorrow with other fixes as well and then close this.
