### ISSUE TITLE
International Numbers sender info

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#6]
When sending an sms to a non-US number, the recipient sees the incoming message number as `sender` and thus cannot reply.
This is the same behavior from **Twilio** and **Telnyx**'s own interface (and not an issue with the app).
Support cases are open with both of them to get to the bottom of this.

Checklist:
- [x] Made sure the number supports sms (not all do)
- [x] Made sure there are no restrictions in the account for international number sending

![us-to-uk](https://user-images.githubusercontent.com/89225730/132800499-7a586dcd-546f-46aa-876e-197c4923cbdd.png)

**Comment by 0perationPrivacy** [comment]
### Solution:
Turn on the toggle for P2P instead of A2P
### Where?
https://portal.telnyx.com/#/app/numbers/my-numbers
On all your numbers, 

1. click on the gear icon on the right
2. go to the `routing` tab
3. switch traffic type to P2P


On my UK number it gave me an error first saying it's not supported on the number. Then I tried it on my US number and the toggle switched. A min later I went back to the UK number and tried to toggle it to P2P and it worked!

Then i sent a test message and now the `sender` is switched with the actual phone number !
Even though there's a red x next to that feature and it says "feature not available for this number", it still works (screenshot of test)


![P2P](https://user-images.githubusercontent.com/89225730/132881316-369655de-536a-4112-be04-12c096be69b5.png)

Before & After (with and without the P2P setting in Twilio)

![with p2p](https://user-images.githubusercontent.com/89225730/132881869-906b2d29-57af-4db6-bba0-4de6ea191d49.png)


> _Next:_ I'm looking into integrating this setting in the API to automate it so the user doesn't have to manually change the setting. Stay tuned. Following up with support.

**Comment by 0perationPrivacy** [comment]
### Unfortunately Twilio does NOT support international sms's using long codes (regular phone numbers).
_(support pointed me to this link as a reference)_
https://www.twilio.com/guidelines/us/sms

![US-LongCodes](https://user-images.githubusercontent.com/89225730/132904881-bb1dc859-1e38-42c6-ab24-064a8c31a17c.png)

**Comment by 0perationPrivacy** [comment]
In my test:
✅ Twilio-US to UK number works
❌ Twilio-UK to US fails

One-way communications 🤷🏽‍♂️

**Comment by PavelNL** [comment]
I was surprised to see this issue as it always worked to me with Telnyx provider. Probably the default for me was just fine (registered in Aug 2021).

Concerning the sending SMS: it never worked for me using a Telnyx +44 number to anywhere outside UK, except to itself. My guess is that this is related to the original +44 phone provider (for me it is "Stour Marine Limited"), which Telnyx has not much control over. I'm glad that at least could receive vertification SMS on a non-primary number ;-)

**Comment by PavelNL** [comment]
Just to be sure I've re-tried the same. This time it took about 10 sec to deliver, the sender field in Telnyx Debug log is still "Sender", but in actual SMS the sender number is different again, this time it shown as from "+33 6 xxx" instead of "(501) xxx". 
At least that delay was a temporary issue.
