### ISSUE TITLE
Black Screen comes over to contacts list when loading messages

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#74]
**Platform:** [Desktop or Mobile]
**Browser:** [e.g. Firefox, Chrome, Safari, Brave]
**App Version:** [e.g v0.60-beta]
**Provider:** [Telnyx, Twilio, Both]

Please edit [e.g v0.60-beta] to 0.72 in template.

**Screenshots**
![BlackScreen](https://user-images.githubusercontent.com/90421861/139751791-8a8e7c6e-605b-4a0e-adb8-26becb72a6c2.png)

**Comment by 0perationPrivacy** [comment]
Yes, very slightly, I thought I fixed that 😜, it came back! On full desktop resolution and mobile resolution you can't see it, but somewhere in between you can,....I'll figure it out and make it disappear. Thanks for the QA on that! I thought I got rid of it. Will work on it next few days.
