### ISSUE TITLE
Icons Missing on Mobile

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#8]
**Platform:** [Mobile]
**Browser:** [ Brave]
**App Version:** [13 Commits]
**Provider:** [Telnyx, Twilio, Both]
### Describe the bug
Compose Message Icon is missing on mobile. On brave browser on mobile I have on Night Mode (Makes Websites dark pages, easy on the eyes)
Turning off the shield does nothing.
If you click the invisible icon the 'compose message' opens

Ps: This number is deleted and had nothing tied to me ever. Don't care if the number is public. :)

**To Reproduce**
1. Go to Appearance in Brave
2. Enable Night Mode (Experimental)
3. Go to the website
4. Icon gone

**Screenshots**
Desktop:
![a](https://user-images.githubusercontent.com/90421861/132931830-ed1171b4-61e7-48d0-93de-c6cea647e6a0.png)
Moblie:
![webapp](https://user-images.githubusercontent.com/90421861/132931833-e0a3b5a6-0eb2-4e71-b88d-95616386cf38.png)

**Comment by privacyosint** [comment]
If you don't get enough donations to keep the project going, please let me know. Want to make sure this project gets all of the road maps

**Comment by 0perationPrivacy** [comment]
I tried to replicate it on iOS, Brave browser, on Dark Mode (not night, and it didn't say experimental anywhere). Seems to work fine, I can see the icons.
(By the way, the version number is shown only on the login screen).
I will have another update pushed in a few hours, see if that make any difference.

**Comment by privacyosint** [comment]
Its on android, linageOS

**Comment by privacyosint** [comment]
I have both android and ios. Android has more features then ios. I love android because ios isn't even close to android experience.

**Comment by privacyosint** [comment]
Also you might want to add a version number right next to beta on the right hand side. I couldn't find the version number until now. Thanks for letting me know.

**Comment by 0perationPrivacy** [comment]
I will get to this once I can emulate it properly, without replicating it, (even in a VM), I'm unable to troubleshoot it. I'm buying a Pixel 5a with GrapheneOS and will test the UI on that. I would assume MOST things will only depend on the browser and not the underlying OS, but very rarely the browser implementation on that OS will render things different. I will investigate shortly and keep this open until then.

**Comment by 0perationPrivacy** [comment]
that BETA ribbon will go away soon, the version is hidden on the bottom of the login screen only. Couldn't find any other place in the UI to insert it, was keeping space for other stuff.
![version](https://user-images.githubusercontent.com/89225730/132933513-d0be7aaf-5925-4308-b520-a6092b68cbde.png)

**Comment by privacyosint** [comment]
oh ok. You don't need to buy a pixel, I can help you maybe..

**Comment by 0perationPrivacy** [comment]
Just bought one 😅 jumping on the bandwagon soon !

**Comment by privacyosint** [comment]
I like linageOS more and it does the same thing. I use the default phone app using VOIP numbers with my contact list.

**Comment by privacyosint** [comment]
It got fixed for now.
![aaa](https://user-images.githubusercontent.com/90421861/135911836-4ff07e03-ae44-49c7-b7b0-010e60a2aa2d.png)
