### ISSUE TITLE
Can't click "Sign Up" button

### ISSUE THREAD

**Issue by vfnilernwreg** [0perationPrivacy/VoIP#80]
- **Platform:**  Desktop and Mobile
- **Browser:**  Firefox, Chrome
- **App Version:** [0.74]
- **Provider:** [Telnyx, Twilio]
- ### Describe the bug
_A clear and concise description of what the bug is_

**To Reproduce**
1. Go to 'https://xxxx.herokuapp.com/'
2. Click on 'Sign Up'
3. Enter new user and password'
4. click Sign up

**Expected behavior**
It should accept the credentials and create a new account

**Actual Behaviors**
Literally nothing happens. No crash, no error, its like somehow you can't click on the button. Its not greyed out and I can click on it but it will not actually "click". I realize this is probably a bizarre issue that "only happens to me". But I tried it on Firefox on my laptop, and on 2 different Chromium Browsers on mobile and it just won't work. Anyone else have an issue like this? Really scratching my head here. Any advice is much appreciated. Thank you so much for making this app and for your assistance!

**Comment by 0perationPrivacy** [comment]
Not bizarre, you likely have a typo in your mongodb link in the environment variables. Check that, the Network tab in firefox will show you some errors in reaching the db as well.

**Comment by vfnilernwreg** [comment]
Thanks for getting back to me @0perationPrivacy
As you suggested, I looked in the network tab in Firefox which revealed a 404 error with the Sign Up POST request:
```POST https://xxx.herokuapp.com/api/api/auth/get-signup[HTTP/1.1 404 Not Found 27ms]```
I then rechecked my connection string for mongodb and found some unintended spaces which I corrected. 
Finally, I redeployed and refreshed the the homepage for the app and now everything works!
Thank you so much for your assistance!

**Comment by 0perationPrivacy** [comment]
> Thanks for getting back to me @0perationPrivacy As you suggested, I looked in the network tab in Firefox which revealed a 404 error with the Sign Up POST request: `POST https://xxx.herokuapp.com/api/api/auth/get-signup[HTTP/1.1 404 Not Found 27ms]` I then rechecked my connection string for mongodb and found some unintended spaces which I corrected. Finally, I redeployed and refreshed the the homepage for the app and now everything works! Thank you so much for your assistance!

Glad I was able to help.
FYI: You do not need to re-deploy if you're changing an environment variable. But doesn't hurt. You can also restart all dynos.
