### ISSUE TITLE
Hardware Key (FIDO U2F)

### ISSUE THREAD

**Issue by 0perationPrivacy** [0perationPrivacy/VoIP#88]
Add option for a hardware key (FIDO U2F), like Yubikey for Multifactor Authentication (MFA).

**Comment by bioscopic** [comment]
Can an (onlykey) https://onlykey.io/ also be coded for use as another option?

**Comment by 0perationPrivacy** [comment]
Yes, I mentioned a product (Yubikey), when I should have mentioned a technology (FIDO U2F).
Anything that supports U2F will be supported.

**Comment by bioscopic** [comment]
Is the current MFA only supporting a soft token (example Authy) or is it possible to add a hardware key? Noticed there is not a logo that populates when adding the soft token MFA option. Is it difficult to add this feature?

**Comment by 0perationPrivacy** [comment]
> Is the current MFA only supporting a soft token (example Authy) or is it possible to add a hardware key? Noticed there is not a logo that populates when adding the soft token MFA option. Is it difficult to add this feature?

Hardware Key option is coming, I've finished coding it but have to test it thoroughly, it was giving me errors. I took a few weeks break to focus on the dashboard project. Hopefully in a week or 2 the hardware key option will be ironed out and released.

**Comment by 0perationPrivacy** [comment]
> Noticed there is not a logo that populates when adding the soft token MFA option. Is it difficult to add this feature?

Can you elaborate on the "logo" part? I don't understand. 🤔

**Comment by bioscopic** [comment]
> > Noticed there is not a logo that populates when adding the soft token MFA option. Is it difficult to add this feature?
> 
> Can you elaborate on the "logo" part? I don't understand. thinking

When a user has Authy installed on their desktop or phone and you add a new MFA account sometimes a logo will appear for the service. For example twitter will have a little graphic of the black bird then the numbers that rotate appear below. This is what im referring to when I say logo. Could the VOIP app have the logo appear when a user uses Authy for example as MFA?

**Comment by 0perationPrivacy** [comment]
ah I see, the logo on the authenticator app! we'll have to investigate where it gets the logo from, the .ico file or some manifest file, both of which i have in there.
I never noticed that as I use either bitwarden's authenticator or keypass's, neither of which have the option of site logo as they are part of the site entry.
