### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by kevin-greenfield** [0perationPrivacy/VoIP#89]
In the xx.herokuapp.com web page, I forgot my password. How do I either reset my password -OR- in the twilio page, how do I free up my phone number by API key reset or changing the messaging handler?

This is great, please keep up the great work!

**Comment by 0perationPrivacy** [comment]
You cannot reset it from the GUI as there's no reset option, we're not collecting an email to reset.
You CAN however delete the password field in mongodb using their online dashboard. Set it to a simple password first by converting it to a bcrypt hash and pasting the value in that field. It should work. Then log into VoIP Suite and change the password there using the menu.

In Twilio I'll have to look it up...don't recall off the top of my head.

**Comment by 0perationPrivacy** [comment]
> In the xx.herokuapp.com web page, I forgot my password. How do I either reset my password -OR- in the twilio page, how do I free up my phone number by API key reset or changing the messaging handler?
> 
> This is great, please keep up the great work!

Twilio API key reset process: https://github.com/0perationPrivacy/voip/wiki/Bonus-Steps#security
