### ISSUE TITLE
Cannot signup

### ISSUE THREAD

**Issue by zmoynihan** [0perationPrivacy/VoIP#9]
**Platform:** Desktop
**Browser:** Safari,Firefox
**App Version:** [e.g v0.60-beta]
**Provider:** Telnyx
### Describe the bug
On the signup page, after putting my credentials in, the Sign up button does nothing.

**To Reproduce**
1. Go to https://nepenthe3.herokuapp.com/signup
2. Click on Sign up
3.

**Expected behavior**

**Screenshots**

**Comment by zmoynihan** [comment]
The Login button does not seem to work either. Safari and Firefox.

**Comment by bioscopic** [comment]
Had the same issue and fixed it after troubleshooting. You need to make sure your configuration in the heroku stack mirrors exactly the directions on inteltechniques website following step by step. Revisit the following steps. Make sure to do them in order. I did mine out of order and had the same issue with the sign up button not accepting the username and password. Also when you are in the heroku stack click on the upper right more option drop down and click restart all dynos. This should fix the issue. 
Click the "Settings" tab
Click "Reveal Config Vars"
Enter "BASE_URL" in the "KEY" field
Scroll down and copy the URL in the "Domains" section (xxx.herokuapp.com)
Paste the URL in the "VALUE" field under the "Config Vars" section
Click "Add"
Enter "DB" in the "KEY" field
Paste the MongoDB "connection string" copied previously into the "VALUE" field
Replace "password" with the password created for the database in the previous MongoDB steps
Be sure to remove the brackets (< >) around the password!
Click "Add"
Enter "COOKIE_KEY" in the empty "KEY" field
Enter 20 random characters in the "VALUE" field
Click "Add"

**Comment by bioscopic** [comment]
After you get it working you should lock it down since you made your URL public! Yikes.
Click "Settings"
Click "Reveal Config Vars"
In the "KEY" field enter "SIGNUPS"
In the "VALUE" field enter "off"
Click "Add"

**Comment by privacyosint** [comment]
I opened this error last night.

https://github.com/0perationPrivacy/VoIP/issues/1

**Comment by 0perationPrivacy** [comment]
This is caused if you enter an incorrect db string.
Make sure the username password is in the same format as in the instructions and examples. I've ignored spaces in the code so don't worry about leading or trailing spaces.

**Comment by zmoynihan** [comment]
Hi,
Thanks for the quick reply. I know there is something small I am missing. I followed MB's guide and double checked my MongoDB and Heroku settings. A screen shot is attached here.

Here is the db string without my login information:
mongodb+srv://<username>:<password>@cluster0.kddvp.mongodb.net/test

<img width="816" alt="VoIP config" src="https://user-images.githubusercontent.com/43887948/132952654-6bcea84c-be53-43aa-98cb-d80ab5ac60c0.png">

**Comment by zmoynihan** [comment]
Ha! I found the problem. I suspect others may run into this as well the special characters in the password of the db string needs to be converted onto percent encoding. I used this site to convert mine: https://www.urlencoder.org/.

Everything works now. Thanks!! This is a great service.

Also, yes bioscopic, I will now lock down the signups since I leaked my domain.

**Comment by 0perationPrivacy** [comment]
Yes, this is specifically called out in the instructions in the Wiki.

**Comment by bioscopic** [comment]
> Ha! I found the problem. I suspect others may run into this as well the special characters in the password of the db string needs to be converted onto percent encoding. I used this site to convert mine: https://www.urlencoder.org/.
> 
> Everything works now. Thanks!! This is a great service.
> 
> Also, yes bioscopic, I will now lock down the signups since I leaked my domain.

Cool nice find and thanks for the URL converter. I had special characters in my password and this was also my problem. Finally, decided to just use lowercase, uppercase and numbers in my password. Now ill go back and update the password to include a few special characters.

**Comment by privacyosint** [comment]
Did this fix your problem?

**Comment by privacyosint** [comment]
If not, please reopen this report. Thank you.
