### ISSUE TITLE
Cannot receive SMS text after latest update

### ISSUE THREAD

**Issue by satirical-muzzle** [0perationPrivacy/VoIP#90]
- **Platform:**  [Mobile]
- **Browser:** [Vanadium]
- **Provider:** [Telnyx]

Since the latest update I have no longer been able to receive SMS text. I can still send SMS as normal.
My latest version of this app was 16 commits behind and texting worked as normal.

The Telnyx webhook logs do not show the incoming messages.

**Comment by 0perationPrivacy** [comment]
v77 is stable.
Redeploy it in heroku, or roll back to a previous deployment under `Activity` and "Roll back to here"

**Comment by 0perationPrivacy** [comment]
I'm looking into this, the message comes in after a refresh but ur right, it doesn't show up unless u refresh the app.

**Comment by 0perationPrivacy** [comment]
update to v79, in the App, go under `Profile Settings` and hit save. That should re-enable the webhook if it got misconfigured.
