### ISSUE TITLE
Does not dial nor "pick up" an incoming call

### ISSUE THREAD

**Issue by satirical-muzzle** [0perationPrivacy/VoIP#95]
On Vanadium w/ Telnyx

Outbound: When I attempt to dial a contact, the dialer window shows, but no call is being placed. Debugger tool on Telnyx shows no outbound calls have been made.

Inbound: App shows call is incoming. I click the green "accept call" button and the screen goes to the dialer window, but the call is not "picked up" and the phone placing the call to the Telnyx VoIP continues to ring.

*There should be no conflict from Linphone as Telnyx no longer routes calls to Linphone since a sip connection is not being used on my number now that the app is assigned to my number.

**Comment by 0perationPrivacy** [comment]
Try it with v79, hit `save` under your Profile Settings, that will reconfigure the messaging and calling profiles in case you modified them in the backend.
If you already have a call setting applied, it will ask to overwrite it. Click yes.

I tried on Vanadium on Graphene just now on the latest version, can place and receive calls on a Telnyx number.
Does it work on a desktop browser?

**Comment by satirical-muzzle** [comment]
I re-saved in Profile Settings and clicked yes. Still same results.
It works on desktop.

**Comment by maliciousactor** [comment]
It looks like the issue is related to the websocket for the call when the application is proxied.

**Comment by maliciousactor** [comment]
I fixed the websocket issue be modifying my reverse proxy configuration to upgrade the connection.

Afterwards, I noticed a JS error in my browser console:
`vue.esm.js:1906 TypeError: Cannot read properties of undefined (reading 'newCall')
    at o.toggleCall (CallView.vue:387:1)
    at click (CallView.vue?ba7b:5:4289)
    at Gt (vue.esm.js:1872:1)
    at HTMLButtonElement.n (vue.esm.js:2197:1)
    at HTMLButtonElement.i._wrapper (vue.esm.js:7609:1)`

**Comment by 0perationPrivacy** [comment]
> It looks like the issue is related to the websocket for the call when the application is proxied.

Can you explain better what you mean by "when it's proxied" ?

**Comment by maliciousactor** [comment]
NGINX is configured to act as a reverse proxy for the application.

**Comment by 0perationPrivacy** [comment]
> I have NGINX configured as a reverse proxy for the application.

I have not tested it with NGINX, but there is configuration in the code to handle up to 1 proxy. I have tested it with cloudflare as the proxy and it works fine. That's how the live public site is set up (voip.operationprivacy.com)

I would say test it without a proxy first, if the URL changes, the you need to hit save on the profile again so that the provider side URL settings are updated for the webhook to work.

**Comment by satirical-muzzle** [comment]
I tried again today and I can now make and receive calls through the app on mobile. I did not make any changes to the app or Telnyx settings. This may be an intermittent issue, though it appears to be working at the moment.

**Comment by maliciousactor** [comment]
@0perationPrivacy Are the websockets configured to use port 3000?

**Comment by 0perationPrivacy** [comment]
> @0perationPrivacy Are the websockets configured to use port 3000?

No, but the backend server runs on port 3000
