### ISSUE TITLE
Call conflicts with Linphone

### ISSUE THREAD

**Issue by vfnilernwreg** [0perationPrivacy/VoIP#98]
- **Platform:**  [Mobile]
- **Browser:** [N/A]
- **App Version:** [e.g v0.80]
- **Provider:** [Twilio]
- ### Describe the bug
- 
_I no longer receive calls on Linphone on my mobile after the calling feature of this app went live recently.
Before, I received SMS on this app, but when someone called me, the call would go to Linphone.
I am effectively unable to receive calls to my Twilio numbers on my phone.

My question; Is there a way to tell Twilio to route calls to Linphone but keep routing SMS to this app? Or is that not possible?

I realize this question might be out of the scope of this page, but I don't know where else to ask and I really need to fix this.
Any guidance is much appreciated! Thank you for all your hard work!

More info:
I run a self hosted instance of this app. The SMS features work fine.

I looked in the Twilio logs and it shows incoming calls being routed to "client:xxxxxxxxxxxxxx", which I assume is related to the TWiML App profile for this app. Before the calling feature for this app went live, incoming calls were handled via the TWiML bins that I set up as per the steps in "Extreme Privacy", and the Twilio logs showed calls being routed to "sip:#######@voipdomain.sip.us1.twilio.com". A call would ring on Linphone on both my laptop and my mobile, but SMS would go to this app, as expected._

**To Reproduce**
1. Follow the guide to self host this app with Twillio as the back end. SMS features working correctly as expected.
2. Make a call from a "normal number" to your Twillio number.
3. The call rings in this app (If the browser is open) but not on Linphone. Attempting to answer to call in this app causes the call to end automatically (known issue?).
4. No errors reported in the Twilio logs.

**Expected behavior**
SMS messages should pop up in this app (They do), but calls should ring on Linphone instead.

Thank you again for any guidance!

**Comment by 0perationPrivacy** [comment]
Yes, this was configured in the latest update.
First configure the call settings for Linphone.
Then go to a profile in VoIP Suite, `Profile Settings` and hit `save`
It will prompt you to either override the call settings that exist, or only configure the sms settings. Choose `No, Keep Old` and it will not touch the call settings you've already done.

**Comment by vfnilernwreg** [comment]
My Linphone settings (TWiML bins) were already in place from before. Can I just go ahead and click "edit" + "save" for the bins and then go to Profile in VoiP Suite and hit save in the profile for the prompt? Or should I delete and re-add the TWiML bins for Linphone?

**Comment by 0perationPrivacy** [comment]
yes, just hit save and don't overright. As long as ur TWiML bin settings are there for linphone in Twilio and assigned to the number, calls should work.

**Comment by vfnilernwreg** [comment]
Ok Thanks so much for helping me out! 
It did not work at first, because the incoming call settings in Twilio had already been changed when I updated VoiP Suite. 

However, using this suggestion as a starting point + revisiting the Extreme Privacy steps for Twilio setup, I have resolved the issue! 

Let me review what worked in case it might help someone else in the future:

Assuming Twilio calls were previously working with Linphone while SMS is setup and coming in through VoiP Suite:

1. I went to Twilio dashboard, "Develop" tab: Phone Numbers > Manage > Active Numbers.
2. Select the number(s) in question
3. Scroll down to Voice & Fax
4. For "A Call Comes in" select TwiML Bin and choose your incomingcall bin from the drop menu
5. Delete whatever is in the "Call Status Changes" area
6. Save

In the future to receive calls again in VoiP Suite, I imagine you can go into the "Profile Settings" in VoiP Suite and click "Save" to accept the new configs?

**Comment by 0perationPrivacy** [comment]
Great, yes, that is correct.
If you want to use VoIP Suite to make and accept calls, then you save and ask it to override whatever call settings exist.
In the future when it has a native mobile app, it will be useful. Right now browser based calls are not great.
