### ISSUE TITLE
Not receiving any SMS message from non-cell orginator

### ISSUE THREAD

**Issue by kramer9** [0perationPrivacy/VoIP#99]
- **Platform:**  Desktop
- **Browser:** [Brave]
- **App Version:** [e.g v0.8]
- **Provider:** [Telnyx]
- ### Describe the bug
I am unable to receive any SMS message, other then those from a cellphone.  I tried adding this number to receive alternative SMS messages for MFA.

**To Reproduce**
Tested using vtext

Error: Invalid user address

Error message below:
550 - Requested action not taken: no such user here

Message details:
  Subject:
  Sent date: Fri Dec 03 15:48:22 UTC 2021
  MAIL FROM: \*\*\*\*\*\*@\*\*\*\*\*\*.com
  RCPT TO: \*\*\*\*\*\*@vtext.com
  From: "\*\*\*\*\*\*@" <******@@******@.com>
  To: "******@vtext.com" <\*\*\*\*\*\*@vtext.com>

  Size: 10.4 KiB
  Number of lines: 61

**Expected behavior**
Receive text message

**Comment by 0perationPrivacy** [comment]
I'm not familiar with vtext but it seems that in the address book of the VoIP Suite, you can only put in numbers and not emails. vtext may be sending it different with a from address that's an email. It may be an issue with the voip provider not accepting it. Will need to check the logs on Telnyx if it even receives or rejects it.
